// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goods.proto

package goods

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoodsInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock                uint32   `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Category             uint32   `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	Brand                string   `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsInfo) Reset()         { *m = GoodsInfo{} }
func (m *GoodsInfo) String() string { return proto.CompactTextString(m) }
func (*GoodsInfo) ProtoMessage()    {}
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{0}
}

func (m *GoodsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsInfo.Unmarshal(m, b)
}
func (m *GoodsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsInfo.Marshal(b, m, deterministic)
}
func (m *GoodsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsInfo.Merge(m, src)
}
func (m *GoodsInfo) XXX_Size() int {
	return xxx_messageInfo_GoodsInfo.Size(m)
}
func (m *GoodsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsInfo proto.InternalMessageInfo

func (m *GoodsInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoodsInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GoodsInfo) GetStock() uint32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *GoodsInfo) GetCategory() uint32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *GoodsInfo) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type AddGoodsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock                uint32   `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Category             uint32   `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	Brand                string   `protobuf:"bytes,5,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGoodsRequest) Reset()         { *m = AddGoodsRequest{} }
func (m *AddGoodsRequest) String() string { return proto.CompactTextString(m) }
func (*AddGoodsRequest) ProtoMessage()    {}
func (*AddGoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{1}
}

func (m *AddGoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGoodsRequest.Unmarshal(m, b)
}
func (m *AddGoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGoodsRequest.Marshal(b, m, deterministic)
}
func (m *AddGoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGoodsRequest.Merge(m, src)
}
func (m *AddGoodsRequest) XXX_Size() int {
	return xxx_messageInfo_AddGoodsRequest.Size(m)
}
func (m *AddGoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGoodsRequest proto.InternalMessageInfo

func (m *AddGoodsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddGoodsRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddGoodsRequest) GetStock() uint32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *AddGoodsRequest) GetCategory() uint32 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *AddGoodsRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type AddGoodsResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	GoodsID              string   `protobuf:"bytes,3,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGoodsResponse) Reset()         { *m = AddGoodsResponse{} }
func (m *AddGoodsResponse) String() string { return proto.CompactTextString(m) }
func (*AddGoodsResponse) ProtoMessage()    {}
func (*AddGoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{2}
}

func (m *AddGoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGoodsResponse.Unmarshal(m, b)
}
func (m *AddGoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGoodsResponse.Marshal(b, m, deterministic)
}
func (m *AddGoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGoodsResponse.Merge(m, src)
}
func (m *AddGoodsResponse) XXX_Size() int {
	return xxx_messageInfo_AddGoodsResponse.Size(m)
}
func (m *AddGoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddGoodsResponse proto.InternalMessageInfo

func (m *AddGoodsResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddGoodsResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *AddGoodsResponse) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

type GetGoodsRequest struct {
	GoodsID              string   `protobuf:"bytes,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsRequest) Reset()         { *m = GetGoodsRequest{} }
func (m *GetGoodsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoodsRequest) ProtoMessage()    {}
func (*GetGoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{3}
}

func (m *GetGoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsRequest.Unmarshal(m, b)
}
func (m *GetGoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsRequest.Marshal(b, m, deterministic)
}
func (m *GetGoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsRequest.Merge(m, src)
}
func (m *GetGoodsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoodsRequest.Size(m)
}
func (m *GetGoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsRequest proto.InternalMessageInfo

func (m *GetGoodsRequest) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

type GetGoodsResponse struct {
	Code                 uint32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string     `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	GoodsInfo            *GoodsInfo `protobuf:"bytes,3,opt,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetGoodsResponse) Reset()         { *m = GetGoodsResponse{} }
func (m *GetGoodsResponse) String() string { return proto.CompactTextString(m) }
func (*GetGoodsResponse) ProtoMessage()    {}
func (*GetGoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{4}
}

func (m *GetGoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsResponse.Unmarshal(m, b)
}
func (m *GetGoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsResponse.Marshal(b, m, deterministic)
}
func (m *GetGoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsResponse.Merge(m, src)
}
func (m *GetGoodsResponse) XXX_Size() int {
	return xxx_messageInfo_GetGoodsResponse.Size(m)
}
func (m *GetGoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsResponse proto.InternalMessageInfo

func (m *GetGoodsResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetGoodsResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetGoodsResponse) GetGoodsInfo() *GoodsInfo {
	if m != nil {
		return m.GoodsInfo
	}
	return nil
}

type GetGoodsListByCategoryRequest struct {
	Category             uint32   `protobuf:"varint,1,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsListByCategoryRequest) Reset()         { *m = GetGoodsListByCategoryRequest{} }
func (m *GetGoodsListByCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoodsListByCategoryRequest) ProtoMessage()    {}
func (*GetGoodsListByCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{5}
}

func (m *GetGoodsListByCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsListByCategoryRequest.Unmarshal(m, b)
}
func (m *GetGoodsListByCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsListByCategoryRequest.Marshal(b, m, deterministic)
}
func (m *GetGoodsListByCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsListByCategoryRequest.Merge(m, src)
}
func (m *GetGoodsListByCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoodsListByCategoryRequest.Size(m)
}
func (m *GetGoodsListByCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsListByCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsListByCategoryRequest proto.InternalMessageInfo

func (m *GetGoodsListByCategoryRequest) GetCategory() uint32 {
	if m != nil {
		return m.Category
	}
	return 0
}

type GetGoodsListByCategoryResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	GoodsIDList          []string `protobuf:"bytes,3,rep,name=goodsIDList,proto3" json:"goodsIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsListByCategoryResponse) Reset()         { *m = GetGoodsListByCategoryResponse{} }
func (m *GetGoodsListByCategoryResponse) String() string { return proto.CompactTextString(m) }
func (*GetGoodsListByCategoryResponse) ProtoMessage()    {}
func (*GetGoodsListByCategoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{6}
}

func (m *GetGoodsListByCategoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsListByCategoryResponse.Unmarshal(m, b)
}
func (m *GetGoodsListByCategoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsListByCategoryResponse.Marshal(b, m, deterministic)
}
func (m *GetGoodsListByCategoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsListByCategoryResponse.Merge(m, src)
}
func (m *GetGoodsListByCategoryResponse) XXX_Size() int {
	return xxx_messageInfo_GetGoodsListByCategoryResponse.Size(m)
}
func (m *GetGoodsListByCategoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsListByCategoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsListByCategoryResponse proto.InternalMessageInfo

func (m *GetGoodsListByCategoryResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetGoodsListByCategoryResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetGoodsListByCategoryResponse) GetGoodsIDList() []string {
	if m != nil {
		return m.GoodsIDList
	}
	return nil
}

type ModifyGoodsInfoRequest struct {
	GoodsID              string     `protobuf:"bytes,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	GoodsInfo            *GoodsInfo `protobuf:"bytes,2,opt,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ModifyGoodsInfoRequest) Reset()         { *m = ModifyGoodsInfoRequest{} }
func (m *ModifyGoodsInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyGoodsInfoRequest) ProtoMessage()    {}
func (*ModifyGoodsInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{7}
}

func (m *ModifyGoodsInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGoodsInfoRequest.Unmarshal(m, b)
}
func (m *ModifyGoodsInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGoodsInfoRequest.Marshal(b, m, deterministic)
}
func (m *ModifyGoodsInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGoodsInfoRequest.Merge(m, src)
}
func (m *ModifyGoodsInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyGoodsInfoRequest.Size(m)
}
func (m *ModifyGoodsInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGoodsInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGoodsInfoRequest proto.InternalMessageInfo

func (m *ModifyGoodsInfoRequest) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

func (m *ModifyGoodsInfoRequest) GetGoodsInfo() *GoodsInfo {
	if m != nil {
		return m.GoodsInfo
	}
	return nil
}

type ModifyGoodsInfoResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyGoodsInfoResponse) Reset()         { *m = ModifyGoodsInfoResponse{} }
func (m *ModifyGoodsInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyGoodsInfoResponse) ProtoMessage()    {}
func (*ModifyGoodsInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{8}
}

func (m *ModifyGoodsInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyGoodsInfoResponse.Unmarshal(m, b)
}
func (m *ModifyGoodsInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyGoodsInfoResponse.Marshal(b, m, deterministic)
}
func (m *ModifyGoodsInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyGoodsInfoResponse.Merge(m, src)
}
func (m *ModifyGoodsInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyGoodsInfoResponse.Size(m)
}
func (m *ModifyGoodsInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyGoodsInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyGoodsInfoResponse proto.InternalMessageInfo

func (m *ModifyGoodsInfoResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModifyGoodsInfoResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type DelGoodsRequest struct {
	GoodsID              string   `protobuf:"bytes,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelGoodsRequest) Reset()         { *m = DelGoodsRequest{} }
func (m *DelGoodsRequest) String() string { return proto.CompactTextString(m) }
func (*DelGoodsRequest) ProtoMessage()    {}
func (*DelGoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{9}
}

func (m *DelGoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelGoodsRequest.Unmarshal(m, b)
}
func (m *DelGoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelGoodsRequest.Marshal(b, m, deterministic)
}
func (m *DelGoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelGoodsRequest.Merge(m, src)
}
func (m *DelGoodsRequest) XXX_Size() int {
	return xxx_messageInfo_DelGoodsRequest.Size(m)
}
func (m *DelGoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelGoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelGoodsRequest proto.InternalMessageInfo

func (m *DelGoodsRequest) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

type DelGoodsResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelGoodsResponse) Reset()         { *m = DelGoodsResponse{} }
func (m *DelGoodsResponse) String() string { return proto.CompactTextString(m) }
func (*DelGoodsResponse) ProtoMessage()    {}
func (*DelGoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{10}
}

func (m *DelGoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelGoodsResponse.Unmarshal(m, b)
}
func (m *DelGoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelGoodsResponse.Marshal(b, m, deterministic)
}
func (m *DelGoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelGoodsResponse.Merge(m, src)
}
func (m *DelGoodsResponse) XXX_Size() int {
	return xxx_messageInfo_DelGoodsResponse.Size(m)
}
func (m *DelGoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelGoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelGoodsResponse proto.InternalMessageInfo

func (m *DelGoodsResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelGoodsResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*GoodsInfo)(nil), "goods.GoodsInfo")
	proto.RegisterType((*AddGoodsRequest)(nil), "goods.AddGoodsRequest")
	proto.RegisterType((*AddGoodsResponse)(nil), "goods.AddGoodsResponse")
	proto.RegisterType((*GetGoodsRequest)(nil), "goods.GetGoodsRequest")
	proto.RegisterType((*GetGoodsResponse)(nil), "goods.GetGoodsResponse")
	proto.RegisterType((*GetGoodsListByCategoryRequest)(nil), "goods.GetGoodsListByCategoryRequest")
	proto.RegisterType((*GetGoodsListByCategoryResponse)(nil), "goods.GetGoodsListByCategoryResponse")
	proto.RegisterType((*ModifyGoodsInfoRequest)(nil), "goods.ModifyGoodsInfoRequest")
	proto.RegisterType((*ModifyGoodsInfoResponse)(nil), "goods.ModifyGoodsInfoResponse")
	proto.RegisterType((*DelGoodsRequest)(nil), "goods.DelGoodsRequest")
	proto.RegisterType((*DelGoodsResponse)(nil), "goods.DelGoodsResponse")
}

func init() { proto.RegisterFile("goods.proto", fileDescriptor_a30593c5487368b0) }

var fileDescriptor_a30593c5487368b0 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0x76, 0x8c, 0xee, 0x9a, 0xe7, 0x8a, 0x61, 0x58, 0x34, 0x04, 0x94, 0x30, 0xec, 0x42, 0x60,
	0xc1, 0x83, 0x7b, 0x5c, 0x16, 0xf6, 0x87, 0x20, 0x42, 0xbd, 0x4c, 0x6f, 0xbd, 0x69, 0x32, 0x06,
	0x69, 0x9b, 0x49, 0x93, 0xb4, 0xe0, 0xa1, 0xa7, 0x5e, 0xfa, 0x67, 0x97, 0x99, 0x64, 0xf2, 0x4b,
	0xc5, 0x92, 0x4b, 0x4f, 0x99, 0x37, 0xf3, 0xbe, 0x79, 0xdf, 0x7b, 0xdf, 0x37, 0x81, 0xbe, 0xcf,
	0xb9, 0x17, 0xcf, 0xc2, 0x88, 0x27, 0x1c, 0x77, 0x65, 0x40, 0x9e, 0x41, 0x5f, 0x8a, 0xc5, 0x2a,
	0xd8, 0x71, 0x8c, 0xa1, 0x13, 0x6c, 0xee, 0x99, 0x89, 0x6c, 0xe4, 0xe8, 0x54, 0xae, 0xf1, 0x57,
	0xe8, 0x86, 0xd1, 0xde, 0x65, 0x66, 0xdb, 0x46, 0x0e, 0xa2, 0x69, 0x20, 0x76, 0xe3, 0x84, 0xbb,
	0xb7, 0xa6, 0x66, 0x23, 0x67, 0x40, 0xd3, 0x00, 0x5b, 0xd0, 0x73, 0x37, 0x09, 0xf3, 0x79, 0x74,
	0x30, 0x3b, 0xf2, 0x20, 0x8f, 0x05, 0x62, 0x1b, 0x6d, 0x02, 0xcf, 0xec, 0xca, 0xcb, 0xd3, 0x80,
	0xbc, 0x20, 0x18, 0xfe, 0xf5, 0x3c, 0x49, 0x81, 0xb2, 0x87, 0x47, 0x16, 0x27, 0x1f, 0xc0, 0xe2,
	0x06, 0x8c, 0x82, 0x44, 0x1c, 0xf2, 0x20, 0x66, 0x82, 0x85, 0xcb, 0xbd, 0x94, 0xc5, 0x80, 0xca,
	0x35, 0x36, 0xe1, 0xb3, 0xf8, 0xae, 0x63, 0x5f, 0xf2, 0xd0, 0xa9, 0x0a, 0xc5, 0x89, 0x9c, 0xe7,
	0x6a, 0x21, 0xb9, 0xe8, 0x54, 0x85, 0xe4, 0x07, 0x0c, 0x97, 0x2c, 0xa9, 0x34, 0x58, 0x4a, 0x46,
	0xd5, 0xe4, 0x10, 0x8c, 0x22, 0xb9, 0x11, 0x91, 0x19, 0xe8, 0xbe, 0xd2, 0x53, 0x52, 0xe9, 0xcf,
	0x8d, 0x59, 0xaa, 0x7b, 0xae, 0x33, 0x2d, 0x52, 0xc8, 0x2f, 0x98, 0xa8, 0x8a, 0x57, 0xfb, 0x38,
	0xf9, 0x77, 0xf8, 0x9f, 0x8d, 0x4a, 0x91, 0x2d, 0x4f, 0x13, 0x55, 0xa7, 0x49, 0x42, 0x98, 0x9e,
	0x03, 0x37, 0x22, 0x6f, 0x67, 0x16, 0x5d, 0x2d, 0xc4, 0x75, 0xa6, 0x66, 0x6b, 0x8e, 0x4e, 0xcb,
	0x5b, 0x64, 0x0b, 0xa3, 0x35, 0xf7, 0xf6, 0xbb, 0x43, 0xd1, 0xcc, 0xa5, 0xa1, 0x56, 0x47, 0xd2,
	0xbe, 0x3c, 0x92, 0x25, 0x8c, 0x8f, 0x6a, 0x34, 0x69, 0x47, 0x48, 0xbf, 0x60, 0x77, 0xef, 0x94,
	0xfe, 0x0f, 0x18, 0x45, 0x72, 0x93, 0x72, 0xf3, 0x57, 0x0d, 0xbe, 0x48, 0xfc, 0x35, 0x8b, 0x9e,
	0xc4, 0xf3, 0xf8, 0x0d, 0x3d, 0x65, 0x6b, 0x3c, 0xca, 0x3a, 0xae, 0x3d, 0x36, 0x6b, 0x7c, 0xb4,
	0x9f, 0xd6, 0x26, 0x2d, 0x01, 0x57, 0xea, 0xe6, 0xf0, 0x9a, 0x95, 0x73, 0x78, 0xdd, 0xb5, 0xa4,
	0x85, 0x7d, 0x18, 0x9d, 0x36, 0x07, 0xfe, 0x56, 0x03, 0x9d, 0x34, 0x9e, 0xf5, 0xfd, 0x42, 0x56,
	0x5e, 0x88, 0xc2, 0xb0, 0xa6, 0x17, 0x9e, 0x64, 0xd8, 0xd3, 0x5e, 0xb1, 0xa6, 0xe7, 0x8e, 0xcb,
	0xbd, 0x2b, 0x35, 0xf2, 0xde, 0x6b, 0x5a, 0xe6, 0xbd, 0xd7, 0x65, 0x23, 0xad, 0xed, 0x27, 0xf9,
	0x8f, 0xfd, 0xf9, 0x16, 0x00, 0x00, 0xff, 0xff, 0x66, 0x65, 0xa1, 0xa8, 0x72, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodsServiceClient is the client API for GoodsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodsServiceClient interface {
	AddGoods(ctx context.Context, in *AddGoodsRequest, opts ...grpc.CallOption) (*AddGoodsResponse, error)
	GetGoods(ctx context.Context, in *GetGoodsRequest, opts ...grpc.CallOption) (*GetGoodsResponse, error)
	GetGoodsListByCategory(ctx context.Context, in *GetGoodsListByCategoryRequest, opts ...grpc.CallOption) (*GetGoodsListByCategoryResponse, error)
	ModifyGoodsInfo(ctx context.Context, in *ModifyGoodsInfoRequest, opts ...grpc.CallOption) (*ModifyGoodsInfoResponse, error)
	DelGoods(ctx context.Context, in *DelGoodsRequest, opts ...grpc.CallOption) (*DelGoodsResponse, error)
}

type goodsServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoodsServiceClient(cc *grpc.ClientConn) GoodsServiceClient {
	return &goodsServiceClient{cc}
}

func (c *goodsServiceClient) AddGoods(ctx context.Context, in *AddGoodsRequest, opts ...grpc.CallOption) (*AddGoodsResponse, error) {
	out := new(AddGoodsResponse)
	err := c.cc.Invoke(ctx, "/goods.GoodsService/AddGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) GetGoods(ctx context.Context, in *GetGoodsRequest, opts ...grpc.CallOption) (*GetGoodsResponse, error) {
	out := new(GetGoodsResponse)
	err := c.cc.Invoke(ctx, "/goods.GoodsService/GetGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) GetGoodsListByCategory(ctx context.Context, in *GetGoodsListByCategoryRequest, opts ...grpc.CallOption) (*GetGoodsListByCategoryResponse, error) {
	out := new(GetGoodsListByCategoryResponse)
	err := c.cc.Invoke(ctx, "/goods.GoodsService/GetGoodsListByCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) ModifyGoodsInfo(ctx context.Context, in *ModifyGoodsInfoRequest, opts ...grpc.CallOption) (*ModifyGoodsInfoResponse, error) {
	out := new(ModifyGoodsInfoResponse)
	err := c.cc.Invoke(ctx, "/goods.GoodsService/ModifyGoodsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsServiceClient) DelGoods(ctx context.Context, in *DelGoodsRequest, opts ...grpc.CallOption) (*DelGoodsResponse, error) {
	out := new(DelGoodsResponse)
	err := c.cc.Invoke(ctx, "/goods.GoodsService/DelGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServiceServer is the server API for GoodsService service.
type GoodsServiceServer interface {
	AddGoods(context.Context, *AddGoodsRequest) (*AddGoodsResponse, error)
	GetGoods(context.Context, *GetGoodsRequest) (*GetGoodsResponse, error)
	GetGoodsListByCategory(context.Context, *GetGoodsListByCategoryRequest) (*GetGoodsListByCategoryResponse, error)
	ModifyGoodsInfo(context.Context, *ModifyGoodsInfoRequest) (*ModifyGoodsInfoResponse, error)
	DelGoods(context.Context, *DelGoodsRequest) (*DelGoodsResponse, error)
}

func RegisterGoodsServiceServer(s *grpc.Server, srv GoodsServiceServer) {
	s.RegisterService(&_GoodsService_serviceDesc, srv)
}

func _GoodsService_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.GoodsService/AddGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).AddGoods(ctx, req.(*AddGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_GetGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.GoodsService/GetGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetGoods(ctx, req.(*GetGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_GetGoodsListByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsListByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetGoodsListByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.GoodsService/GetGoodsListByCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetGoodsListByCategory(ctx, req.(*GetGoodsListByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_ModifyGoodsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyGoodsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).ModifyGoodsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.GoodsService/ModifyGoodsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).ModifyGoodsInfo(ctx, req.(*ModifyGoodsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsService_DelGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).DelGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods.GoodsService/DelGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).DelGoods(ctx, req.(*DelGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goods.GoodsService",
	HandlerType: (*GoodsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGoods",
			Handler:    _GoodsService_AddGoods_Handler,
		},
		{
			MethodName: "GetGoods",
			Handler:    _GoodsService_GetGoods_Handler,
		},
		{
			MethodName: "GetGoodsListByCategory",
			Handler:    _GoodsService_GetGoodsListByCategory_Handler,
		},
		{
			MethodName: "ModifyGoodsInfo",
			Handler:    _GoodsService_ModifyGoodsInfo_Handler,
		},
		{
			MethodName: "DelGoods",
			Handler:    _GoodsService_DelGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
