# app config
log:
  logPath: log/order_service.log            # 日志文件路径
  logLevel: info

etcd:
  endpoints:
    - 192.168.1.7:2379
    - 192.168.1.10:2379
    - 192.168.1.11:2379

server:
  name: order-core-service
  port: 6070

httpServer:
  port: 4584

database:
  address: 192.168.1.100:3306
  username: root
  password: 180498
  driverName: mysql
  dbName: ant_test

redis:
  address: 192.168.1.7:7001
  password: 123456
  redisLockTimeout: 5     #分布式锁超时时间,单位秒

kafka:
  addrs: 
    - 192.168.1.7:9092
    - 192.168.1.10:9092
    - 192.168.1.11:9092

nsq:
  addrs: 
    - 192.168.1.7:4150

client:
  userServiceName: user-core-service
  goodsServiceName: goods-core-service