// Code generated by protoc-gen-go. DO NOT EDIT.
// source: strategymanager.proto

package strategymanager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartStrategyRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SecretKey            string   `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,5,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	StrategyName         string   `protobuf:"bytes,6,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	InstrumentId         string   `protobuf:"bytes,7,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Endpoint             string   `protobuf:"bytes,8,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	WsEndpoint           string   `protobuf:"bytes,9,opt,name=ws_endpoint,json=wsEndpoint,proto3" json:"ws_endpoint,omitempty"`
	Params               string   `protobuf:"bytes,10,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStrategyRequest) Reset()         { *m = StartStrategyRequest{} }
func (m *StartStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*StartStrategyRequest) ProtoMessage()    {}
func (*StartStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e316c09d5f1b9b5, []int{0}
}

func (m *StartStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStrategyRequest.Unmarshal(m, b)
}
func (m *StartStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStrategyRequest.Marshal(b, m, deterministic)
}
func (m *StartStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStrategyRequest.Merge(m, src)
}
func (m *StartStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_StartStrategyRequest.Size(m)
}
func (m *StartStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartStrategyRequest proto.InternalMessageInfo

func (m *StartStrategyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StartStrategyRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *StartStrategyRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *StartStrategyRequest) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *StartStrategyRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *StartStrategyRequest) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *StartStrategyRequest) GetInstrumentId() string {
	if m != nil {
		return m.InstrumentId
	}
	return ""
}

func (m *StartStrategyRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *StartStrategyRequest) GetWsEndpoint() string {
	if m != nil {
		return m.WsEndpoint
	}
	return ""
}

func (m *StartStrategyRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type StartStrategyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStrategyResponse) Reset()         { *m = StartStrategyResponse{} }
func (m *StartStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*StartStrategyResponse) ProtoMessage()    {}
func (*StartStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e316c09d5f1b9b5, []int{1}
}

func (m *StartStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStrategyResponse.Unmarshal(m, b)
}
func (m *StartStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStrategyResponse.Marshal(b, m, deterministic)
}
func (m *StartStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStrategyResponse.Merge(m, src)
}
func (m *StartStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_StartStrategyResponse.Size(m)
}
func (m *StartStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartStrategyResponse proto.InternalMessageInfo

type StopStrategyRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	StrategyName         string   `protobuf:"bytes,4,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	InstrumentId         string   `protobuf:"bytes,5,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopStrategyRequest) Reset()         { *m = StopStrategyRequest{} }
func (m *StopStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*StopStrategyRequest) ProtoMessage()    {}
func (*StopStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e316c09d5f1b9b5, []int{2}
}

func (m *StopStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopStrategyRequest.Unmarshal(m, b)
}
func (m *StopStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopStrategyRequest.Marshal(b, m, deterministic)
}
func (m *StopStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopStrategyRequest.Merge(m, src)
}
func (m *StopStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_StopStrategyRequest.Size(m)
}
func (m *StopStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopStrategyRequest proto.InternalMessageInfo

func (m *StopStrategyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StopStrategyRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *StopStrategyRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *StopStrategyRequest) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *StopStrategyRequest) GetInstrumentId() string {
	if m != nil {
		return m.InstrumentId
	}
	return ""
}

type StopStrategyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopStrategyResponse) Reset()         { *m = StopStrategyResponse{} }
func (m *StopStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*StopStrategyResponse) ProtoMessage()    {}
func (*StopStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e316c09d5f1b9b5, []int{3}
}

func (m *StopStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopStrategyResponse.Unmarshal(m, b)
}
func (m *StopStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopStrategyResponse.Marshal(b, m, deterministic)
}
func (m *StopStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopStrategyResponse.Merge(m, src)
}
func (m *StopStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_StopStrategyResponse.Size(m)
}
func (m *StopStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopStrategyResponse proto.InternalMessageInfo

type StrategyExecRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	StrategyName         string   `protobuf:"bytes,4,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	InstrumentId         string   `protobuf:"bytes,5,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Params               string   `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyExecRequest) Reset()         { *m = StrategyExecRequest{} }
func (m *StrategyExecRequest) String() string { return proto.CompactTextString(m) }
func (*StrategyExecRequest) ProtoMessage()    {}
func (*StrategyExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e316c09d5f1b9b5, []int{4}
}

func (m *StrategyExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyExecRequest.Unmarshal(m, b)
}
func (m *StrategyExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyExecRequest.Marshal(b, m, deterministic)
}
func (m *StrategyExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyExecRequest.Merge(m, src)
}
func (m *StrategyExecRequest) XXX_Size() int {
	return xxx_messageInfo_StrategyExecRequest.Size(m)
}
func (m *StrategyExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyExecRequest proto.InternalMessageInfo

func (m *StrategyExecRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StrategyExecRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *StrategyExecRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *StrategyExecRequest) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *StrategyExecRequest) GetInstrumentId() string {
	if m != nil {
		return m.InstrumentId
	}
	return ""
}

func (m *StrategyExecRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type StrategyExecResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyExecResponse) Reset()         { *m = StrategyExecResponse{} }
func (m *StrategyExecResponse) String() string { return proto.CompactTextString(m) }
func (*StrategyExecResponse) ProtoMessage()    {}
func (*StrategyExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e316c09d5f1b9b5, []int{5}
}

func (m *StrategyExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyExecResponse.Unmarshal(m, b)
}
func (m *StrategyExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyExecResponse.Marshal(b, m, deterministic)
}
func (m *StrategyExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyExecResponse.Merge(m, src)
}
func (m *StrategyExecResponse) XXX_Size() int {
	return xxx_messageInfo_StrategyExecResponse.Size(m)
}
func (m *StrategyExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyExecResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartStrategyRequest)(nil), "strategymanager.StartStrategyRequest")
	proto.RegisterType((*StartStrategyResponse)(nil), "strategymanager.StartStrategyResponse")
	proto.RegisterType((*StopStrategyRequest)(nil), "strategymanager.StopStrategyRequest")
	proto.RegisterType((*StopStrategyResponse)(nil), "strategymanager.StopStrategyResponse")
	proto.RegisterType((*StrategyExecRequest)(nil), "strategymanager.StrategyExecRequest")
	proto.RegisterType((*StrategyExecResponse)(nil), "strategymanager.StrategyExecResponse")
}

func init() { proto.RegisterFile("strategymanager.proto", fileDescriptor_4e316c09d5f1b9b5) }

var fileDescriptor_4e316c09d5f1b9b5 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x05, 0x3e, 0x28, 0x70, 0x3f, 0x08, 0xc9, 0x28, 0x30, 0x21, 0xf1, 0x27, 0x55, 0x8c, 0x2b,
	0x16, 0xfa, 0x0c, 0x2c, 0x8c, 0xd1, 0x05, 0xac, 0x4d, 0x1d, 0xe1, 0x06, 0x1a, 0xd3, 0xe9, 0x38,
	0x33, 0x04, 0x78, 0x28, 0x17, 0xbe, 0x82, 0x89, 0xef, 0x65, 0x3a, 0xd3, 0x42, 0xa1, 0x4d, 0x70,
	0x63, 0xe2, 0xf2, 0x9e, 0x73, 0x66, 0x72, 0xce, 0xb9, 0x9d, 0x42, 0x5b, 0x69, 0xc9, 0x34, 0xce,
	0xd6, 0x01, 0xe3, 0x6c, 0x86, 0x72, 0x20, 0x64, 0xa8, 0x43, 0xd2, 0xda, 0x83, 0xdd, 0xcf, 0x12,
	0x1c, 0x8f, 0x35, 0x93, 0x7a, 0x1c, 0x13, 0x23, 0x7c, 0x5b, 0xa0, 0xd2, 0xa4, 0x0b, 0xd5, 0x85,
	0x42, 0xe9, 0xf9, 0x53, 0x5a, 0x3c, 0x2f, 0x5e, 0xd7, 0x47, 0x4e, 0x34, 0xde, 0x4d, 0x49, 0x0f,
	0x6a, 0xb8, 0x9a, 0xcc, 0x19, 0x9f, 0x21, 0x2d, 0x19, 0x66, 0x33, 0x47, 0x87, 0x98, 0xf0, 0xbd,
	0x57, 0x5c, 0xd3, 0x7f, 0xf6, 0x10, 0x13, 0xfe, 0x3d, 0xae, 0xc9, 0x09, 0x80, 0xc2, 0x89, 0x44,
	0x6d, 0xb8, 0xb2, 0xe1, 0xea, 0x16, 0x89, 0xe8, 0x53, 0x00, 0xc1, 0x94, 0x12, 0x73, 0xc9, 0x14,
	0xd2, 0x8a, 0xa1, 0x53, 0x08, 0xb9, 0x80, 0x66, 0x62, 0xdc, 0xe3, 0x2c, 0x40, 0xea, 0x18, 0x49,
	0x23, 0x01, 0x1f, 0x59, 0x60, 0x44, 0x3e, 0x57, 0x5a, 0x2e, 0x02, 0xe4, 0x3a, 0xf2, 0x5d, 0xb5,
	0xa2, 0x2d, 0x18, 0xbb, 0xe7, 0x53, 0x11, 0xfa, 0x5c, 0xd3, 0x5a, 0xec, 0x3e, 0x9e, 0xc9, 0x19,
	0xfc, 0x5f, 0x2a, 0x6f, 0x43, 0xd7, 0xad, 0x8d, 0xa5, 0x1a, 0x26, 0x82, 0x0e, 0x38, 0x82, 0x49,
	0x16, 0x28, 0x0a, 0x36, 0x9d, 0x9d, 0xdc, 0x2e, 0xb4, 0xf7, 0x3a, 0x54, 0x22, 0xe4, 0x0a, 0xdd,
	0xf7, 0x22, 0x1c, 0x8d, 0x75, 0x28, 0x7e, 0xb7, 0xdc, 0x4c, 0x3b, 0xe5, 0x9f, 0xb4, 0x53, 0xc9,
	0xb6, 0xe3, 0x76, 0xa2, 0x8f, 0x21, 0x6d, 0x37, 0xce, 0xf1, 0x65, 0x72, 0x58, 0x70, 0xb8, 0xc2,
	0xc9, 0x1f, 0xcf, 0x91, 0x5a, 0x94, 0xb3, 0xb3, 0x28, 0x93, 0x2f, 0x1d, 0xc3, 0xe6, 0xbb, 0xf9,
	0x28, 0x41, 0x2b, 0x21, 0x1e, 0xec, 0xcb, 0x20, 0xcf, 0xd0, 0xdc, 0x59, 0x2a, 0xe9, 0x0f, 0xf6,
	0xdf, 0x54, 0xde, 0xc3, 0xe9, 0x5d, 0x1d, 0x92, 0xc5, 0x9d, 0x16, 0xc8, 0x13, 0x34, 0xd2, 0x6d,
	0x93, 0xcb, 0x9c, 0x93, 0x99, 0x6f, 0xa7, 0xd7, 0x3f, 0xa0, 0xda, 0xbd, 0x7e, 0x1b, 0x36, 0xf7,
	0xfa, 0xcc, 0x4a, 0x73, 0xaf, 0xcf, 0x36, 0xe6, 0x16, 0x5e, 0x1c, 0xf3, 0x47, 0xb9, 0xfd, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x02, 0xd2, 0x37, 0xad, 0x6a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StrategyManagerClient is the client API for StrategyManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrategyManagerClient interface {
	StartStrategy(ctx context.Context, in *StartStrategyRequest, opts ...grpc.CallOption) (*StartStrategyResponse, error)
	StopStrategy(ctx context.Context, in *StopStrategyRequest, opts ...grpc.CallOption) (*StopStrategyResponse, error)
	StrategyExec(ctx context.Context, in *StrategyExecRequest, opts ...grpc.CallOption) (*StrategyExecResponse, error)
}

type strategyManagerClient struct {
	cc *grpc.ClientConn
}

func NewStrategyManagerClient(cc *grpc.ClientConn) StrategyManagerClient {
	return &strategyManagerClient{cc}
}

func (c *strategyManagerClient) StartStrategy(ctx context.Context, in *StartStrategyRequest, opts ...grpc.CallOption) (*StartStrategyResponse, error) {
	out := new(StartStrategyResponse)
	err := c.cc.Invoke(ctx, "/strategymanager.StrategyManager/StartStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyManagerClient) StopStrategy(ctx context.Context, in *StopStrategyRequest, opts ...grpc.CallOption) (*StopStrategyResponse, error) {
	out := new(StopStrategyResponse)
	err := c.cc.Invoke(ctx, "/strategymanager.StrategyManager/StopStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyManagerClient) StrategyExec(ctx context.Context, in *StrategyExecRequest, opts ...grpc.CallOption) (*StrategyExecResponse, error) {
	out := new(StrategyExecResponse)
	err := c.cc.Invoke(ctx, "/strategymanager.StrategyManager/StrategyExec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyManagerServer is the server API for StrategyManager service.
type StrategyManagerServer interface {
	StartStrategy(context.Context, *StartStrategyRequest) (*StartStrategyResponse, error)
	StopStrategy(context.Context, *StopStrategyRequest) (*StopStrategyResponse, error)
	StrategyExec(context.Context, *StrategyExecRequest) (*StrategyExecResponse, error)
}

func RegisterStrategyManagerServer(s *grpc.Server, srv StrategyManagerServer) {
	s.RegisterService(&_StrategyManager_serviceDesc, srv)
}

func _StrategyManager_StartStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyManagerServer).StartStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategymanager.StrategyManager/StartStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyManagerServer).StartStrategy(ctx, req.(*StartStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyManager_StopStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyManagerServer).StopStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategymanager.StrategyManager/StopStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyManagerServer).StopStrategy(ctx, req.(*StopStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyManager_StrategyExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyManagerServer).StrategyExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategymanager.StrategyManager/StrategyExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyManagerServer).StrategyExec(ctx, req.(*StrategyExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StrategyManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "strategymanager.StrategyManager",
	HandlerType: (*StrategyManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStrategy",
			Handler:    _StrategyManager_StartStrategy_Handler,
		},
		{
			MethodName: "StopStrategy",
			Handler:    _StrategyManager_StopStrategy_Handler,
		},
		{
			MethodName: "StrategyExec",
			Handler:    _StrategyManager_StrategyExec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strategymanager.proto",
}
