# app config
log:
  logPath: log/goods_service.log            # 日志文件路径
  logLevel: info

etcd:
  endpoints:
    - 192.168.1.7:2379
    - 192.168.1.10:2379
    - 192.168.1.11:2379

server:
  name: goods-core-service
  port: 6069

httpServer:
  port: 4583

database:
  address: 192.168.1.100:3306
  username: root
  password: 180498
  driverName: mysql
  dbName: ant_test

redis:
  address: 192.168.1.7:7001
  password: 123456
  redisLockTimeout: 5     #分布式锁超时时间,单位秒

mongo:
  address: 192.168.1.10:10001
  username: admin
  password: 123456
  dbName: ant_test

client:
  userServiceName: user-core-service