// Code generated by protoc-gen-go. DO NOT EDIT.
// source: strategy.proto

package strategy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartStrategyRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SecretKey            string   `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,5,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	StrategyName         string   `protobuf:"bytes,6,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	InstrumentId         string   `protobuf:"bytes,7,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Endpoint             string   `protobuf:"bytes,8,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	WsEndpoint           string   `protobuf:"bytes,9,opt,name=ws_endpoint,json=wsEndpoint,proto3" json:"ws_endpoint,omitempty"`
	Params               string   `protobuf:"bytes,10,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStrategyRequest) Reset()         { *m = StartStrategyRequest{} }
func (m *StartStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*StartStrategyRequest) ProtoMessage()    {}
func (*StartStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ec5ce6dd46feab, []int{0}
}

func (m *StartStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStrategyRequest.Unmarshal(m, b)
}
func (m *StartStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStrategyRequest.Marshal(b, m, deterministic)
}
func (m *StartStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStrategyRequest.Merge(m, src)
}
func (m *StartStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_StartStrategyRequest.Size(m)
}
func (m *StartStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartStrategyRequest proto.InternalMessageInfo

func (m *StartStrategyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StartStrategyRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *StartStrategyRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *StartStrategyRequest) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *StartStrategyRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *StartStrategyRequest) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *StartStrategyRequest) GetInstrumentId() string {
	if m != nil {
		return m.InstrumentId
	}
	return ""
}

func (m *StartStrategyRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *StartStrategyRequest) GetWsEndpoint() string {
	if m != nil {
		return m.WsEndpoint
	}
	return ""
}

func (m *StartStrategyRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type StartStrategyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStrategyResponse) Reset()         { *m = StartStrategyResponse{} }
func (m *StartStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*StartStrategyResponse) ProtoMessage()    {}
func (*StartStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ec5ce6dd46feab, []int{1}
}

func (m *StartStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStrategyResponse.Unmarshal(m, b)
}
func (m *StartStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStrategyResponse.Marshal(b, m, deterministic)
}
func (m *StartStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStrategyResponse.Merge(m, src)
}
func (m *StartStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_StartStrategyResponse.Size(m)
}
func (m *StartStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartStrategyResponse proto.InternalMessageInfo

type StopStrategyRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	StrategyName         string   `protobuf:"bytes,4,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	InstrumentId         string   `protobuf:"bytes,5,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopStrategyRequest) Reset()         { *m = StopStrategyRequest{} }
func (m *StopStrategyRequest) String() string { return proto.CompactTextString(m) }
func (*StopStrategyRequest) ProtoMessage()    {}
func (*StopStrategyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ec5ce6dd46feab, []int{2}
}

func (m *StopStrategyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopStrategyRequest.Unmarshal(m, b)
}
func (m *StopStrategyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopStrategyRequest.Marshal(b, m, deterministic)
}
func (m *StopStrategyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopStrategyRequest.Merge(m, src)
}
func (m *StopStrategyRequest) XXX_Size() int {
	return xxx_messageInfo_StopStrategyRequest.Size(m)
}
func (m *StopStrategyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopStrategyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopStrategyRequest proto.InternalMessageInfo

func (m *StopStrategyRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StopStrategyRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *StopStrategyRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *StopStrategyRequest) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *StopStrategyRequest) GetInstrumentId() string {
	if m != nil {
		return m.InstrumentId
	}
	return ""
}

type StopStrategyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopStrategyResponse) Reset()         { *m = StopStrategyResponse{} }
func (m *StopStrategyResponse) String() string { return proto.CompactTextString(m) }
func (*StopStrategyResponse) ProtoMessage()    {}
func (*StopStrategyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ec5ce6dd46feab, []int{3}
}

func (m *StopStrategyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopStrategyResponse.Unmarshal(m, b)
}
func (m *StopStrategyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopStrategyResponse.Marshal(b, m, deterministic)
}
func (m *StopStrategyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopStrategyResponse.Merge(m, src)
}
func (m *StopStrategyResponse) XXX_Size() int {
	return xxx_messageInfo_StopStrategyResponse.Size(m)
}
func (m *StopStrategyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopStrategyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopStrategyResponse proto.InternalMessageInfo

type StrategyExecRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ApiKey               string   `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	StrategyName         string   `protobuf:"bytes,4,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	InstrumentId         string   `protobuf:"bytes,5,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Params               string   `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyExecRequest) Reset()         { *m = StrategyExecRequest{} }
func (m *StrategyExecRequest) String() string { return proto.CompactTextString(m) }
func (*StrategyExecRequest) ProtoMessage()    {}
func (*StrategyExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ec5ce6dd46feab, []int{4}
}

func (m *StrategyExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyExecRequest.Unmarshal(m, b)
}
func (m *StrategyExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyExecRequest.Marshal(b, m, deterministic)
}
func (m *StrategyExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyExecRequest.Merge(m, src)
}
func (m *StrategyExecRequest) XXX_Size() int {
	return xxx_messageInfo_StrategyExecRequest.Size(m)
}
func (m *StrategyExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyExecRequest proto.InternalMessageInfo

func (m *StrategyExecRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StrategyExecRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *StrategyExecRequest) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *StrategyExecRequest) GetStrategyName() string {
	if m != nil {
		return m.StrategyName
	}
	return ""
}

func (m *StrategyExecRequest) GetInstrumentId() string {
	if m != nil {
		return m.InstrumentId
	}
	return ""
}

func (m *StrategyExecRequest) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

type StrategyExecResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrategyExecResponse) Reset()         { *m = StrategyExecResponse{} }
func (m *StrategyExecResponse) String() string { return proto.CompactTextString(m) }
func (*StrategyExecResponse) ProtoMessage()    {}
func (*StrategyExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46ec5ce6dd46feab, []int{5}
}

func (m *StrategyExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyExecResponse.Unmarshal(m, b)
}
func (m *StrategyExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyExecResponse.Marshal(b, m, deterministic)
}
func (m *StrategyExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyExecResponse.Merge(m, src)
}
func (m *StrategyExecResponse) XXX_Size() int {
	return xxx_messageInfo_StrategyExecResponse.Size(m)
}
func (m *StrategyExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyExecResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StartStrategyRequest)(nil), "strategy.StartStrategyRequest")
	proto.RegisterType((*StartStrategyResponse)(nil), "strategy.StartStrategyResponse")
	proto.RegisterType((*StopStrategyRequest)(nil), "strategy.StopStrategyRequest")
	proto.RegisterType((*StopStrategyResponse)(nil), "strategy.StopStrategyResponse")
	proto.RegisterType((*StrategyExecRequest)(nil), "strategy.StrategyExecRequest")
	proto.RegisterType((*StrategyExecResponse)(nil), "strategy.StrategyExecResponse")
}

func init() { proto.RegisterFile("strategy.proto", fileDescriptor_46ec5ce6dd46feab) }

var fileDescriptor_46ec5ce6dd46feab = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x05, 0x84, 0x52, 0x46, 0xf0, 0xb0, 0x2a, 0x34, 0x24, 0x80, 0xa9, 0x17, 0x4f, 0x1c, 0xf4,
	0x1b, 0x38, 0x18, 0x13, 0x4d, 0xe0, 0x03, 0x9a, 0x15, 0x26, 0xd0, 0x98, 0x6e, 0xd7, 0x9d, 0x25,
	0xc0, 0xcd, 0x1f, 0xf2, 0x27, 0x4c, 0xfc, 0x2f, 0xd3, 0xdd, 0x16, 0x5a, 0x2b, 0x89, 0x17, 0x13,
	0x8f, 0xf3, 0xde, 0xcc, 0xe4, 0xbd, 0x37, 0xdd, 0xc2, 0x19, 0x69, 0xc5, 0x35, 0x2e, 0x77, 0x63,
	0xa9, 0x62, 0x1d, 0x33, 0x37, 0xab, 0xfd, 0x8f, 0x1a, 0x5c, 0xcc, 0x34, 0x57, 0x7a, 0x96, 0x22,
	0x53, 0x7c, 0x5d, 0x23, 0x69, 0xd6, 0x83, 0xe6, 0x9a, 0x50, 0x05, 0xe1, 0xc2, 0xab, 0x5e, 0x55,
	0x6f, 0x5a, 0x53, 0x27, 0x29, 0xef, 0x17, 0xac, 0x0f, 0x2e, 0x6e, 0xe7, 0x2b, 0x2e, 0x96, 0xe8,
	0xd5, 0x0c, 0xb3, 0xaf, 0x93, 0x21, 0x2e, 0xc3, 0xe0, 0x05, 0x77, 0xde, 0x89, 0x1d, 0xe2, 0x32,
	0x7c, 0xc0, 0x1d, 0x1b, 0x00, 0x10, 0xce, 0x15, 0x6a, 0xc3, 0xd5, 0x0d, 0xd7, 0xb2, 0x48, 0x42,
	0x0f, 0x01, 0x24, 0x27, 0x92, 0x2b, 0xc5, 0x09, 0xbd, 0x86, 0xa1, 0x73, 0x08, 0xbb, 0x86, 0x4e,
	0xa6, 0x38, 0x10, 0x3c, 0x42, 0xcf, 0x31, 0x2d, 0xed, 0x0c, 0x7c, 0xe4, 0x91, 0x69, 0x0a, 0x05,
	0x69, 0xb5, 0x8e, 0x50, 0xe8, 0x44, 0x77, 0xd3, 0x36, 0x1d, 0xc0, 0x54, 0xbd, 0x58, 0xc8, 0x38,
	0x14, 0xda, 0x73, 0x53, 0xf5, 0x69, 0xcd, 0x46, 0x70, 0xba, 0xa1, 0x60, 0x4f, 0xb7, 0xac, 0x8c,
	0x0d, 0x4d, 0xb2, 0x86, 0x2e, 0x38, 0x92, 0x2b, 0x1e, 0x91, 0x07, 0xd6, 0x9d, 0xad, 0xfc, 0x1e,
	0x5c, 0x7e, 0xcb, 0x90, 0x64, 0x2c, 0x08, 0xfd, 0xf7, 0x2a, 0x9c, 0xcf, 0x74, 0x2c, 0xff, 0x36,
	0xdc, 0x52, 0x3a, 0xf5, 0xdf, 0xa4, 0xd3, 0x28, 0xa7, 0xe3, 0x77, 0x93, 0x8f, 0x21, 0x2f, 0x37,
	0xf5, 0xf1, 0x69, 0x7c, 0x58, 0x70, 0xb2, 0xc5, 0xf9, 0x3f, 0xf7, 0x91, 0x3b, 0x94, 0x53, 0x38,
	0x94, 0xf1, 0x97, 0xb7, 0x61, 0xfd, 0xdd, 0xbe, 0xd5, 0xc0, 0xcd, 0x08, 0x36, 0x85, 0x4e, 0xe1,
	0x9a, 0x6c, 0x38, 0xde, 0x3f, 0x9f, 0x9f, 0x9e, 0x4a, 0x7f, 0x74, 0x94, 0x4f, 0xe3, 0xab, 0xb0,
	0x27, 0x68, 0xe7, 0x83, 0x65, 0x83, 0xfc, 0x48, 0xe9, 0xfb, 0xe8, 0x0f, 0x8f, 0xd1, 0xc5, 0x85,
	0x07, 0x27, 0xc5, 0x85, 0xa5, 0x43, 0x15, 0x17, 0x96, 0x03, 0xf0, 0x2b, 0xcf, 0x8e, 0xf9, 0x33,
	0xdc, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0x98, 0xbf, 0x57, 0xcf, 0x2b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StrategyClient is the client API for Strategy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StrategyClient interface {
	StartStrategy(ctx context.Context, in *StartStrategyRequest, opts ...grpc.CallOption) (*StartStrategyResponse, error)
	StopStrategy(ctx context.Context, in *StopStrategyRequest, opts ...grpc.CallOption) (*StopStrategyResponse, error)
	StrategyExec(ctx context.Context, in *StrategyExecRequest, opts ...grpc.CallOption) (*StrategyExecResponse, error)
}

type strategyClient struct {
	cc *grpc.ClientConn
}

func NewStrategyClient(cc *grpc.ClientConn) StrategyClient {
	return &strategyClient{cc}
}

func (c *strategyClient) StartStrategy(ctx context.Context, in *StartStrategyRequest, opts ...grpc.CallOption) (*StartStrategyResponse, error) {
	out := new(StartStrategyResponse)
	err := c.cc.Invoke(ctx, "/strategy.Strategy/StartStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) StopStrategy(ctx context.Context, in *StopStrategyRequest, opts ...grpc.CallOption) (*StopStrategyResponse, error) {
	out := new(StopStrategyResponse)
	err := c.cc.Invoke(ctx, "/strategy.Strategy/StopStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyClient) StrategyExec(ctx context.Context, in *StrategyExecRequest, opts ...grpc.CallOption) (*StrategyExecResponse, error) {
	out := new(StrategyExecResponse)
	err := c.cc.Invoke(ctx, "/strategy.Strategy/StrategyExec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServer is the server API for Strategy service.
type StrategyServer interface {
	StartStrategy(context.Context, *StartStrategyRequest) (*StartStrategyResponse, error)
	StopStrategy(context.Context, *StopStrategyRequest) (*StopStrategyResponse, error)
	StrategyExec(context.Context, *StrategyExecRequest) (*StrategyExecResponse, error)
}

func RegisterStrategyServer(s *grpc.Server, srv StrategyServer) {
	s.RegisterService(&_Strategy_serviceDesc, srv)
}

func _Strategy_StartStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).StartStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategy.Strategy/StartStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).StartStrategy(ctx, req.(*StartStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_StopStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).StopStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategy.Strategy/StopStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).StopStrategy(ctx, req.(*StopStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Strategy_StrategyExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrategyExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServer).StrategyExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/strategy.Strategy/StrategyExec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServer).StrategyExec(ctx, req.(*StrategyExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Strategy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "strategy.Strategy",
	HandlerType: (*StrategyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStrategy",
			Handler:    _Strategy_StartStrategy_Handler,
		},
		{
			MethodName: "StopStrategy",
			Handler:    _Strategy_StopStrategy_Handler,
		},
		{
			MethodName: "StrategyExec",
			Handler:    _Strategy_StrategyExec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strategy.proto",
}
