# app config
log:
  logPath: log/user_service.log            # 日志文件路径
  logLevel: info

etcd:
  endpoints:
    - 0.0.0.0:2379

grpcServer:
  name: user-core-service
  port: 6068

httpServer:
  port: 4582

process:
  path: /data/strategy

database:
  address: 192.168.126.128:3306
  username: root
  password: 180498
  driverName: mysql
  dbName: skydb