// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderInfo struct {
	SellerID             string   `protobuf:"bytes,1,opt,name=sellerID,proto3" json:"sellerID,omitempty"`
	BuyerID              string   `protobuf:"bytes,2,opt,name=buyerID,proto3" json:"buyerID,omitempty"`
	GoodsID              string   `protobuf:"bytes,3,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	GoodsName            string   `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Pay                  float64  `protobuf:"fixed64,6,opt,name=pay,proto3" json:"pay,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetSellerID() string {
	if m != nil {
		return m.SellerID
	}
	return ""
}

func (m *OrderInfo) GetBuyerID() string {
	if m != nil {
		return m.BuyerID
	}
	return ""
}

func (m *OrderInfo) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

func (m *OrderInfo) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *OrderInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderInfo) GetPay() float64 {
	if m != nil {
		return m.Pay
	}
	return 0
}

func (m *OrderInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AddOrderRequest struct {
	BuyerID              string   `protobuf:"bytes,1,opt,name=buyerID,proto3" json:"buyerID,omitempty"`
	GoodsID              string   `protobuf:"bytes,2,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderRequest) Reset()         { *m = AddOrderRequest{} }
func (m *AddOrderRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrderRequest) ProtoMessage()    {}
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *AddOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderRequest.Unmarshal(m, b)
}
func (m *AddOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderRequest.Marshal(b, m, deterministic)
}
func (m *AddOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderRequest.Merge(m, src)
}
func (m *AddOrderRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrderRequest.Size(m)
}
func (m *AddOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderRequest proto.InternalMessageInfo

func (m *AddOrderRequest) GetBuyerID() string {
	if m != nil {
		return m.BuyerID
	}
	return ""
}

func (m *AddOrderRequest) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

type AddOrderResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	OrderID              string   `protobuf:"bytes,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderResponse) Reset()         { *m = AddOrderResponse{} }
func (m *AddOrderResponse) String() string { return proto.CompactTextString(m) }
func (*AddOrderResponse) ProtoMessage()    {}
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *AddOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderResponse.Unmarshal(m, b)
}
func (m *AddOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderResponse.Marshal(b, m, deterministic)
}
func (m *AddOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderResponse.Merge(m, src)
}
func (m *AddOrderResponse) XXX_Size() int {
	return xxx_messageInfo_AddOrderResponse.Size(m)
}
func (m *AddOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderResponse proto.InternalMessageInfo

func (m *AddOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *AddOrderResponse) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type GetOrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type GetOrderResponse struct {
	Code                 uint32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string     `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	OrderInfo            *OrderInfo `protobuf:"bytes,3,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetOrderResponse) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

type DelOrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOrderRequest) Reset()         { *m = DelOrderRequest{} }
func (m *DelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DelOrderRequest) ProtoMessage()    {}
func (*DelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *DelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOrderRequest.Unmarshal(m, b)
}
func (m *DelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOrderRequest.Marshal(b, m, deterministic)
}
func (m *DelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOrderRequest.Merge(m, src)
}
func (m *DelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DelOrderRequest.Size(m)
}
func (m *DelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelOrderRequest proto.InternalMessageInfo

func (m *DelOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type DelOrderResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOrderResponse) Reset()         { *m = DelOrderResponse{} }
func (m *DelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DelOrderResponse) ProtoMessage()    {}
func (*DelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *DelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOrderResponse.Unmarshal(m, b)
}
func (m *DelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOrderResponse.Marshal(b, m, deterministic)
}
func (m *DelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOrderResponse.Merge(m, src)
}
func (m *DelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DelOrderResponse.Size(m)
}
func (m *DelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelOrderResponse proto.InternalMessageInfo

func (m *DelOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderInfo)(nil), "order.OrderInfo")
	proto.RegisterType((*AddOrderRequest)(nil), "order.AddOrderRequest")
	proto.RegisterType((*AddOrderResponse)(nil), "order.AddOrderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "order.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "order.GetOrderResponse")
	proto.RegisterType((*DelOrderRequest)(nil), "order.DelOrderRequest")
	proto.RegisterType((*DelOrderResponse)(nil), "order.DelOrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xed, 0xf6, 0x3b, 0x53, 0x4b, 0xc3, 0x22, 0x75, 0x29, 0x1e, 0x4a, 0x4e, 0x05, 0xa1, 0x87,
	0x7a, 0x16, 0x14, 0x2a, 0xd2, 0x83, 0x0a, 0xf1, 0xe6, 0xad, 0x6d, 0xc6, 0x22, 0xd4, 0x6e, 0xcc,
	0x26, 0x42, 0x7f, 0x9a, 0xbf, 0xc1, 0x3f, 0x25, 0x3b, 0xc9, 0xee, 0xda, 0x15, 0x41, 0x7a, 0xea,
	0xbc, 0x79, 0xf3, 0xa6, 0x6f, 0xdf, 0x10, 0xe8, 0xc9, 0x2c, 0xc1, 0x6c, 0x9a, 0x66, 0x32, 0x97,
	0xbc, 0x45, 0x20, 0xfa, 0x64, 0x10, 0x3c, 0xea, 0x6a, 0xb1, 0x7b, 0x91, 0x7c, 0x04, 0x5d, 0x85,
	0xdb, 0x2d, 0x66, 0x8b, 0xb9, 0x60, 0x63, 0x36, 0x09, 0x62, 0x8b, 0xb9, 0x80, 0xce, 0xaa, 0xd8,
	0x13, 0x55, 0x27, 0xca, 0x40, 0xcd, 0x6c, 0xa4, 0x4c, 0xd4, 0x62, 0x2e, 0x1a, 0x25, 0x53, 0x41,
	0x7e, 0x0e, 0x01, 0x95, 0x0f, 0xcb, 0x37, 0x14, 0x4d, 0xe2, 0x5c, 0x83, 0x9f, 0x42, 0x2b, 0xcd,
	0x5e, 0xd7, 0x28, 0x5a, 0x63, 0x36, 0x61, 0x71, 0x09, 0x78, 0x08, 0x8d, 0x74, 0xb9, 0x17, 0x6d,
	0xea, 0xe9, 0x92, 0x0f, 0xa1, 0xad, 0xf2, 0x65, 0x5e, 0x28, 0xd1, 0x19, 0xb3, 0x49, 0x3f, 0xae,
	0x50, 0x74, 0x0b, 0x83, 0x9b, 0x24, 0x21, 0xf7, 0x31, 0xbe, 0x17, 0xa8, 0xf2, 0x9f, 0x26, 0xd9,
	0x9f, 0x26, 0xeb, 0x07, 0x26, 0xa3, 0x67, 0x08, 0xdd, 0x1a, 0x95, 0xca, 0x9d, 0x42, 0xce, 0xa1,
	0xb9, 0x96, 0x09, 0xd2, 0x92, 0x7e, 0x4c, 0xb5, 0xde, 0xa0, 0x7f, 0xef, 0xd5, 0xc6, 0x6c, 0xa8,
	0xa0, 0x66, 0x28, 0x4d, 0x17, 0x40, 0x05, 0xa3, 0x0b, 0x18, 0xdc, 0x61, 0xee, 0x5b, 0x34, 0xc3,
	0xec, 0x70, 0x38, 0x85, 0xd0, 0x0d, 0x1f, 0x65, 0x64, 0x0a, 0x81, 0x34, 0xc7, 0x24, 0x2b, 0xbd,
	0x59, 0x38, 0x2d, 0xaf, 0x6e, 0x8f, 0x1c, 0xbb, 0x11, 0x6d, 0x6f, 0x8e, 0xdb, 0x7f, 0xda, 0xbb,
	0x86, 0xd0, 0x0d, 0x1f, 0x63, 0x6f, 0xf6, 0xc5, 0xe0, 0x84, 0xf4, 0x4f, 0x98, 0x7d, 0xe8, 0x5b,
	0x5f, 0x41, 0xd7, 0x44, 0xcf, 0x87, 0x95, 0x51, 0xef, 0xa4, 0xa3, 0xb3, 0x5f, 0xfd, 0xf2, 0xbf,
	0xa3, 0x9a, 0x96, 0x9b, 0xc0, 0xac, 0xdc, 0x8b, 0xdb, 0xca, 0xfd, 0x64, 0x4b, 0xb9, 0x79, 0x90,
	0x95, 0x7b, 0x71, 0x58, 0xb9, 0xff, 0xf2, 0xa8, 0xb6, 0x6a, 0xd3, 0x87, 0x74, 0xf9, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0xa5, 0x6d, 0x03, 0xa1, 0x57, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	DelOrder(ctx context.Context, in *DelOrderRequest, opts ...grpc.CallOption) (*DelOrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error) {
	out := new(AddOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/AddOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DelOrder(ctx context.Context, in *DelOrderRequest, opts ...grpc.CallOption) (*DelOrderResponse, error) {
	out := new(DelOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/DelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	AddOrder(context.Context, *AddOrderRequest) (*AddOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	DelOrder(context.Context, *DelOrderRequest) (*DelOrderResponse, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/AddOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrder(ctx, req.(*AddOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/DelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DelOrder(ctx, req.(*DelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrder",
			Handler:    _OrderService_AddOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "DelOrder",
			Handler:    _OrderService_DelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
