// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderInfo struct {
	SellerID             string   `protobuf:"bytes,1,opt,name=sellerID,proto3" json:"sellerID,omitempty"`
	BuyerID              string   `protobuf:"bytes,2,opt,name=buyerID,proto3" json:"buyerID,omitempty"`
	GoodsID              string   `protobuf:"bytes,3,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	GoodsName            string   `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	Count                uint32   `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Pay                  float64  `protobuf:"fixed64,7,opt,name=pay,proto3" json:"pay,omitempty"`
	Status               uint32   `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetSellerID() string {
	if m != nil {
		return m.SellerID
	}
	return ""
}

func (m *OrderInfo) GetBuyerID() string {
	if m != nil {
		return m.BuyerID
	}
	return ""
}

func (m *OrderInfo) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

func (m *OrderInfo) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *OrderInfo) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *OrderInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderInfo) GetPay() float64 {
	if m != nil {
		return m.Pay
	}
	return 0
}

func (m *OrderInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type AddOrderRequest struct {
	BuyerID              string   `protobuf:"bytes,1,opt,name=buyerID,proto3" json:"buyerID,omitempty"`
	GoodsID              string   `protobuf:"bytes,2,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderRequest) Reset()         { *m = AddOrderRequest{} }
func (m *AddOrderRequest) String() string { return proto.CompactTextString(m) }
func (*AddOrderRequest) ProtoMessage()    {}
func (*AddOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *AddOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderRequest.Unmarshal(m, b)
}
func (m *AddOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderRequest.Marshal(b, m, deterministic)
}
func (m *AddOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderRequest.Merge(m, src)
}
func (m *AddOrderRequest) XXX_Size() int {
	return xxx_messageInfo_AddOrderRequest.Size(m)
}
func (m *AddOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderRequest proto.InternalMessageInfo

func (m *AddOrderRequest) GetBuyerID() string {
	if m != nil {
		return m.BuyerID
	}
	return ""
}

func (m *AddOrderRequest) GetGoodsID() string {
	if m != nil {
		return m.GoodsID
	}
	return ""
}

func (m *AddOrderRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AddOrderResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	OrderID              string   `protobuf:"bytes,3,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddOrderResponse) Reset()         { *m = AddOrderResponse{} }
func (m *AddOrderResponse) String() string { return proto.CompactTextString(m) }
func (*AddOrderResponse) ProtoMessage()    {}
func (*AddOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *AddOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddOrderResponse.Unmarshal(m, b)
}
func (m *AddOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddOrderResponse.Marshal(b, m, deterministic)
}
func (m *AddOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddOrderResponse.Merge(m, src)
}
func (m *AddOrderResponse) XXX_Size() int {
	return xxx_messageInfo_AddOrderResponse.Size(m)
}
func (m *AddOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddOrderResponse proto.InternalMessageInfo

func (m *AddOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *AddOrderResponse) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type GetOrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type GetOrderResponse struct {
	Code                 uint32     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string     `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	OrderInfo            *OrderInfo `protobuf:"bytes,3,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetOrderResponse) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

type DelOrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOrderRequest) Reset()         { *m = DelOrderRequest{} }
func (m *DelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DelOrderRequest) ProtoMessage()    {}
func (*DelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *DelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOrderRequest.Unmarshal(m, b)
}
func (m *DelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOrderRequest.Marshal(b, m, deterministic)
}
func (m *DelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOrderRequest.Merge(m, src)
}
func (m *DelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DelOrderRequest.Size(m)
}
func (m *DelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelOrderRequest proto.InternalMessageInfo

func (m *DelOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type DelOrderResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelOrderResponse) Reset()         { *m = DelOrderResponse{} }
func (m *DelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DelOrderResponse) ProtoMessage()    {}
func (*DelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *DelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelOrderResponse.Unmarshal(m, b)
}
func (m *DelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelOrderResponse.Marshal(b, m, deterministic)
}
func (m *DelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelOrderResponse.Merge(m, src)
}
func (m *DelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DelOrderResponse.Size(m)
}
func (m *DelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelOrderResponse proto.InternalMessageInfo

func (m *DelOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type PayOrderRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderRequest) Reset()         { *m = PayOrderRequest{} }
func (m *PayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrderRequest) ProtoMessage()    {}
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *PayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderRequest.Unmarshal(m, b)
}
func (m *PayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderRequest.Marshal(b, m, deterministic)
}
func (m *PayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderRequest.Merge(m, src)
}
func (m *PayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrderRequest.Size(m)
}
func (m *PayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderRequest proto.InternalMessageInfo

func (m *PayOrderRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

type PayOrderResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderResponse) Reset()         { *m = PayOrderResponse{} }
func (m *PayOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PayOrderResponse) ProtoMessage()    {}
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *PayOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderResponse.Unmarshal(m, b)
}
func (m *PayOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderResponse.Marshal(b, m, deterministic)
}
func (m *PayOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderResponse.Merge(m, src)
}
func (m *PayOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PayOrderResponse.Size(m)
}
func (m *PayOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderResponse proto.InternalMessageInfo

func (m *PayOrderResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PayOrderResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type SetActivityRequest struct {
	ActivityID           string   `protobuf:"bytes,1,opt,name=activityID,proto3" json:"activityID,omitempty"`
	ActivityName         string   `protobuf:"bytes,2,opt,name=activityName,proto3" json:"activityName,omitempty"`
	StartTime            string   `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetActivityRequest) Reset()         { *m = SetActivityRequest{} }
func (m *SetActivityRequest) String() string { return proto.CompactTextString(m) }
func (*SetActivityRequest) ProtoMessage()    {}
func (*SetActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *SetActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetActivityRequest.Unmarshal(m, b)
}
func (m *SetActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetActivityRequest.Marshal(b, m, deterministic)
}
func (m *SetActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetActivityRequest.Merge(m, src)
}
func (m *SetActivityRequest) XXX_Size() int {
	return xxx_messageInfo_SetActivityRequest.Size(m)
}
func (m *SetActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetActivityRequest proto.InternalMessageInfo

func (m *SetActivityRequest) GetActivityID() string {
	if m != nil {
		return m.ActivityID
	}
	return ""
}

func (m *SetActivityRequest) GetActivityName() string {
	if m != nil {
		return m.ActivityName
	}
	return ""
}

func (m *SetActivityRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *SetActivityRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type SetActivityResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetActivityResponse) Reset()         { *m = SetActivityResponse{} }
func (m *SetActivityResponse) String() string { return proto.CompactTextString(m) }
func (*SetActivityResponse) ProtoMessage()    {}
func (*SetActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *SetActivityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetActivityResponse.Unmarshal(m, b)
}
func (m *SetActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetActivityResponse.Marshal(b, m, deterministic)
}
func (m *SetActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetActivityResponse.Merge(m, src)
}
func (m *SetActivityResponse) XXX_Size() int {
	return xxx_messageInfo_SetActivityResponse.Size(m)
}
func (m *SetActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetActivityResponse proto.InternalMessageInfo

func (m *SetActivityResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SetActivityResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type GetActivityRequest struct {
	ActivityID           string   `protobuf:"bytes,1,opt,name=activityID,proto3" json:"activityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivityRequest) Reset()         { *m = GetActivityRequest{} }
func (m *GetActivityRequest) String() string { return proto.CompactTextString(m) }
func (*GetActivityRequest) ProtoMessage()    {}
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{11}
}

func (m *GetActivityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivityRequest.Unmarshal(m, b)
}
func (m *GetActivityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivityRequest.Marshal(b, m, deterministic)
}
func (m *GetActivityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivityRequest.Merge(m, src)
}
func (m *GetActivityRequest) XXX_Size() int {
	return xxx_messageInfo_GetActivityRequest.Size(m)
}
func (m *GetActivityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivityRequest proto.InternalMessageInfo

func (m *GetActivityRequest) GetActivityID() string {
	if m != nil {
		return m.ActivityID
	}
	return ""
}

type GetActivityResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	ActivityID           string   `protobuf:"bytes,3,opt,name=activityID,proto3" json:"activityID,omitempty"`
	ActivityName         string   `protobuf:"bytes,4,opt,name=activityName,proto3" json:"activityName,omitempty"`
	StartTime            string   `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivityResponse) Reset()         { *m = GetActivityResponse{} }
func (m *GetActivityResponse) String() string { return proto.CompactTextString(m) }
func (*GetActivityResponse) ProtoMessage()    {}
func (*GetActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{12}
}

func (m *GetActivityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivityResponse.Unmarshal(m, b)
}
func (m *GetActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivityResponse.Marshal(b, m, deterministic)
}
func (m *GetActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivityResponse.Merge(m, src)
}
func (m *GetActivityResponse) XXX_Size() int {
	return xxx_messageInfo_GetActivityResponse.Size(m)
}
func (m *GetActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivityResponse proto.InternalMessageInfo

func (m *GetActivityResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetActivityResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetActivityResponse) GetActivityID() string {
	if m != nil {
		return m.ActivityID
	}
	return ""
}

func (m *GetActivityResponse) GetActivityName() string {
	if m != nil {
		return m.ActivityName
	}
	return ""
}

func (m *GetActivityResponse) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetActivityResponse) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GetPayOrderPersonTimeRequest struct {
	Param                string   `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPayOrderPersonTimeRequest) Reset()         { *m = GetPayOrderPersonTimeRequest{} }
func (m *GetPayOrderPersonTimeRequest) String() string { return proto.CompactTextString(m) }
func (*GetPayOrderPersonTimeRequest) ProtoMessage()    {}
func (*GetPayOrderPersonTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{13}
}

func (m *GetPayOrderPersonTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPayOrderPersonTimeRequest.Unmarshal(m, b)
}
func (m *GetPayOrderPersonTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPayOrderPersonTimeRequest.Marshal(b, m, deterministic)
}
func (m *GetPayOrderPersonTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPayOrderPersonTimeRequest.Merge(m, src)
}
func (m *GetPayOrderPersonTimeRequest) XXX_Size() int {
	return xxx_messageInfo_GetPayOrderPersonTimeRequest.Size(m)
}
func (m *GetPayOrderPersonTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPayOrderPersonTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPayOrderPersonTimeRequest proto.InternalMessageInfo

func (m *GetPayOrderPersonTimeRequest) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

type GetPayOrderPersonTimeResponse struct {
	Code                  uint32           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg               string           `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	PersonTime            int64            `protobuf:"varint,3,opt,name=personTime,proto3" json:"personTime,omitempty"`
	PersonList            []string         `protobuf:"bytes,4,rep,name=personList,proto3" json:"personList,omitempty"`
	PersonTimeByTimestamp int64            `protobuf:"varint,5,opt,name=personTimeByTimestamp,proto3" json:"personTimeByTimestamp,omitempty"`
	PersonListMap         map[string]int64 `protobuf:"bytes,6,rep,name=personListMap,proto3" json:"personListMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *GetPayOrderPersonTimeResponse) Reset()         { *m = GetPayOrderPersonTimeResponse{} }
func (m *GetPayOrderPersonTimeResponse) String() string { return proto.CompactTextString(m) }
func (*GetPayOrderPersonTimeResponse) ProtoMessage()    {}
func (*GetPayOrderPersonTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{14}
}

func (m *GetPayOrderPersonTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPayOrderPersonTimeResponse.Unmarshal(m, b)
}
func (m *GetPayOrderPersonTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPayOrderPersonTimeResponse.Marshal(b, m, deterministic)
}
func (m *GetPayOrderPersonTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPayOrderPersonTimeResponse.Merge(m, src)
}
func (m *GetPayOrderPersonTimeResponse) XXX_Size() int {
	return xxx_messageInfo_GetPayOrderPersonTimeResponse.Size(m)
}
func (m *GetPayOrderPersonTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPayOrderPersonTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPayOrderPersonTimeResponse proto.InternalMessageInfo

func (m *GetPayOrderPersonTimeResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetPayOrderPersonTimeResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetPayOrderPersonTimeResponse) GetPersonTime() int64 {
	if m != nil {
		return m.PersonTime
	}
	return 0
}

func (m *GetPayOrderPersonTimeResponse) GetPersonList() []string {
	if m != nil {
		return m.PersonList
	}
	return nil
}

func (m *GetPayOrderPersonTimeResponse) GetPersonTimeByTimestamp() int64 {
	if m != nil {
		return m.PersonTimeByTimestamp
	}
	return 0
}

func (m *GetPayOrderPersonTimeResponse) GetPersonListMap() map[string]int64 {
	if m != nil {
		return m.PersonListMap
	}
	return nil
}

func init() {
	proto.RegisterType((*OrderInfo)(nil), "order.OrderInfo")
	proto.RegisterType((*AddOrderRequest)(nil), "order.AddOrderRequest")
	proto.RegisterType((*AddOrderResponse)(nil), "order.AddOrderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "order.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "order.GetOrderResponse")
	proto.RegisterType((*DelOrderRequest)(nil), "order.DelOrderRequest")
	proto.RegisterType((*DelOrderResponse)(nil), "order.DelOrderResponse")
	proto.RegisterType((*PayOrderRequest)(nil), "order.PayOrderRequest")
	proto.RegisterType((*PayOrderResponse)(nil), "order.PayOrderResponse")
	proto.RegisterType((*SetActivityRequest)(nil), "order.SetActivityRequest")
	proto.RegisterType((*SetActivityResponse)(nil), "order.SetActivityResponse")
	proto.RegisterType((*GetActivityRequest)(nil), "order.GetActivityRequest")
	proto.RegisterType((*GetActivityResponse)(nil), "order.GetActivityResponse")
	proto.RegisterType((*GetPayOrderPersonTimeRequest)(nil), "order.GetPayOrderPersonTimeRequest")
	proto.RegisterType((*GetPayOrderPersonTimeResponse)(nil), "order.GetPayOrderPersonTimeResponse")
	proto.RegisterMapType((map[string]int64)(nil), "order.GetPayOrderPersonTimeResponse.PersonListMapEntry")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xd3, 0x3c,
	0x18, 0x5e, 0x9a, 0xb6, 0x6b, 0xdf, 0xae, 0x5a, 0xe5, 0x7d, 0xdb, 0x17, 0xaa, 0x81, 0xaa, 0xc0,
	0x41, 0x25, 0xa4, 0x1e, 0x94, 0x4a, 0x20, 0x24, 0xa4, 0x0d, 0x0a, 0x51, 0x25, 0x06, 0x55, 0xc6,
	0x11, 0x88, 0x83, 0xac, 0x31, 0x53, 0x45, 0x9b, 0x84, 0xd8, 0xad, 0x94, 0x33, 0x2e, 0x81, 0x3b,
	0xe2, 0x12, 0xb8, 0x09, 0x2e, 0x04, 0xd9, 0x8e, 0xed, 0x24, 0xfd, 0x59, 0x29, 0x27, 0x9b, 0xdf,
	0xff, 0xc7, 0x4f, 0x5e, 0x3f, 0x2a, 0x34, 0xc2, 0xd8, 0xc7, 0x71, 0x2f, 0x8a, 0x43, 0x1a, 0xa2,
	0x0a, 0x37, 0xec, 0x5f, 0x06, 0xd4, 0xdf, 0xb3, 0xd3, 0x28, 0xf8, 0x12, 0xa2, 0x36, 0xd4, 0x08,
	0x9e, 0xcd, 0x70, 0x3c, 0x1a, 0x5a, 0x46, 0xc7, 0xe8, 0xd6, 0x5d, 0x65, 0x23, 0x0b, 0x0e, 0x6f,
	0x16, 0x09, 0x0f, 0x95, 0x78, 0x48, 0x9a, 0x2c, 0x72, 0x1b, 0x86, 0x3e, 0x19, 0x0d, 0x2d, 0x53,
	0x44, 0x52, 0x13, 0x9d, 0x43, 0x9d, 0x1f, 0xdf, 0x79, 0x73, 0x6c, 0x95, 0x79, 0x4c, 0x3b, 0xd0,
	0x7f, 0x50, 0x99, 0x84, 0x8b, 0x80, 0x5a, 0x95, 0x8e, 0xd1, 0x6d, 0xba, 0xc2, 0x60, 0xde, 0x28,
	0x9e, 0x4e, 0xb0, 0x55, 0xed, 0x18, 0x5d, 0xc3, 0x15, 0x06, 0x6a, 0x81, 0x19, 0x79, 0x89, 0x75,
	0xc8, 0x7d, 0xec, 0x88, 0xce, 0xa0, 0x4a, 0xa8, 0x47, 0x17, 0xc4, 0xaa, 0xf1, 0xf2, 0xd4, 0xb2,
	0x3f, 0xc1, 0xf1, 0xa5, 0xef, 0xf3, 0x3b, 0xb9, 0xf8, 0xdb, 0x02, 0x13, 0x9a, 0x85, 0x6e, 0x6c,
	0x84, 0x5e, 0xca, 0x43, 0x57, 0xe0, 0xcc, 0x0c, 0x38, 0xfb, 0x23, 0xb4, 0x74, 0x73, 0x12, 0x85,
	0x01, 0xc1, 0x08, 0x41, 0x79, 0x12, 0xfa, 0x98, 0xb7, 0x6e, 0xba, 0xfc, 0xcc, 0xfa, 0xb2, 0xff,
	0x57, 0xe4, 0x56, 0xf6, 0x4d, 0x4d, 0x16, 0xe1, 0xcc, 0x6b, 0xb2, 0x52, 0xd3, 0x7e, 0x0c, 0xc7,
	0x0e, 0xa6, 0x45, 0xe0, 0x32, 0xd9, 0xc8, 0x27, 0x47, 0xd0, 0xd2, 0xc9, 0x7b, 0x01, 0xe9, 0x41,
	0x3d, 0x94, 0x1f, 0x9e, 0x43, 0x69, 0xf4, 0x5b, 0x3d, 0xb1, 0x21, 0x6a, 0x21, 0x5c, 0x9d, 0xc2,
	0xe0, 0x0d, 0xf1, 0x6c, 0x47, 0x78, 0x17, 0xd0, 0xd2, 0xc9, 0xfb, 0xc0, 0x63, 0xe3, 0xc6, 0x5e,
	0xb2, 0xfb, 0x38, 0x9d, 0xbc, 0xd7, 0xb8, 0x1f, 0x06, 0xa0, 0x6b, 0x4c, 0x2f, 0x27, 0x74, 0xba,
	0x9c, 0xd2, 0x44, 0x8e, 0x7c, 0x00, 0xe0, 0xa5, 0x2e, 0x35, 0x35, 0xe3, 0x41, 0x36, 0x1c, 0x49,
	0x8b, 0xef, 0xb8, 0xe8, 0x9a, 0xf3, 0xb1, 0x47, 0x40, 0xa8, 0x17, 0xd3, 0x0f, 0xd3, 0x39, 0x4e,
	0xbf, 0xb9, 0x76, 0x30, 0x48, 0x38, 0xf0, 0x79, 0x4c, 0x3c, 0x10, 0x69, 0xda, 0xaf, 0xe0, 0x24,
	0x87, 0x68, 0xaf, 0x7b, 0x0d, 0x00, 0x39, 0x7f, 0x7d, 0x2d, 0xfb, 0xa7, 0x01, 0x27, 0xce, 0xbf,
	0xce, 0x2e, 0x4c, 0x31, 0xef, 0x24, 0xaf, 0x7c, 0x17, 0x79, 0x95, 0x2d, 0xe4, 0x55, 0xf3, 0xe4,
	0x0d, 0xe0, 0xdc, 0xc1, 0x54, 0x2e, 0xc5, 0x18, 0xc7, 0x24, 0x0c, 0x58, 0x40, 0x32, 0xc0, 0x54,
	0xc6, 0x8b, 0xbd, 0x79, 0x7a, 0x79, 0x61, 0xd8, 0xbf, 0x4b, 0x70, 0x7f, 0x43, 0xd9, 0xbe, 0x0c,
	0x44, 0xaa, 0x07, 0x67, 0xc0, 0x74, 0x33, 0x1e, 0x1d, 0x7f, 0x3b, 0x25, 0xd4, 0x2a, 0x77, 0x4c,
	0xc6, 0x90, 0xf6, 0xa0, 0x01, 0x9c, 0xea, 0xec, 0x97, 0x09, 0xfb, 0x4b, 0xa8, 0x37, 0x8f, 0x38,
	0x13, 0xa6, 0xbb, 0x3e, 0x88, 0x3e, 0x43, 0x53, 0xf7, 0xb8, 0xf2, 0x22, 0xab, 0xda, 0x31, 0xbb,
	0x8d, 0xfe, 0xd3, 0xf4, 0x75, 0x6f, 0xbd, 0x60, 0x6f, 0x9c, 0xad, 0x7c, 0x1d, 0xd0, 0x38, 0x71,
	0xf3, 0xdd, 0xda, 0x17, 0x80, 0x56, 0x93, 0x98, 0x40, 0x7f, 0xc5, 0x49, 0x4a, 0x27, 0x3b, 0x32,
	0x8a, 0x97, 0xde, 0x6c, 0x21, 0x1e, 0x85, 0xe9, 0x0a, 0xe3, 0x79, 0xe9, 0x99, 0xd1, 0xff, 0x5e,
	0x86, 0x23, 0x3e, 0xff, 0x1a, 0xc7, 0x4b, 0xa6, 0xee, 0x2f, 0xa0, 0x26, 0x65, 0x15, 0x9d, 0xa5,
	0x30, 0x0b, 0x22, 0xde, 0xfe, 0x7f, 0xc5, 0x2f, 0x10, 0xdb, 0x07, 0xac, 0x5c, 0x8a, 0xa1, 0x2a,
	0x2f, 0x48, 0xa9, 0x2a, 0x2f, 0xaa, 0xa6, 0x28, 0x97, 0x62, 0xa5, 0xca, 0x0b, 0x52, 0xa7, 0xca,
	0x8b, 0xaa, 0x26, 0xca, 0x25, 0x9f, 0xaa, 0xbc, 0x20, 0x5d, 0xaa, 0xbc, 0xa8, 0x52, 0xf6, 0x01,
	0x7a, 0x03, 0x8d, 0xcc, 0x33, 0x47, 0xf7, 0xd2, 0xcc, 0x55, 0x31, 0x6a, 0xb7, 0xd7, 0x85, 0xb2,
	0x7d, 0x9c, 0x35, 0x7d, 0x9c, 0xcd, 0x7d, 0x9c, 0xb5, 0x7d, 0x7c, 0x38, 0x5d, 0xbb, 0x21, 0xe8,
	0xe1, 0xf6, 0xfd, 0x11, 0xbd, 0x1f, 0xed, 0xb2, 0x64, 0xf6, 0xc1, 0x4d, 0x95, 0xff, 0x0a, 0x79,
	0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0xce, 0x77, 0xa3, 0x0b, 0x94, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	DelOrder(ctx context.Context, in *DelOrderRequest, opts ...grpc.CallOption) (*DelOrderResponse, error)
	PayOrder(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error)
	SetActivity(ctx context.Context, in *SetActivityRequest, opts ...grpc.CallOption) (*SetActivityResponse, error)
	GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error)
	GetPayOrderPersonTime(ctx context.Context, in *GetPayOrderPersonTimeRequest, opts ...grpc.CallOption) (*GetPayOrderPersonTimeResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error) {
	out := new(AddOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/AddOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DelOrder(ctx context.Context, in *DelOrderRequest, opts ...grpc.CallOption) (*DelOrderResponse, error) {
	out := new(DelOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/DelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) PayOrder(ctx context.Context, in *PayOrderRequest, opts ...grpc.CallOption) (*PayOrderResponse, error) {
	out := new(PayOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/PayOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) SetActivity(ctx context.Context, in *SetActivityRequest, opts ...grpc.CallOption) (*SetActivityResponse, error) {
	out := new(SetActivityResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/SetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*GetActivityResponse, error) {
	out := new(GetActivityResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetPayOrderPersonTime(ctx context.Context, in *GetPayOrderPersonTimeRequest, opts ...grpc.CallOption) (*GetPayOrderPersonTimeResponse, error) {
	out := new(GetPayOrderPersonTimeResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetPayOrderPersonTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	AddOrder(context.Context, *AddOrderRequest) (*AddOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	DelOrder(context.Context, *DelOrderRequest) (*DelOrderResponse, error)
	PayOrder(context.Context, *PayOrderRequest) (*PayOrderResponse, error)
	SetActivity(context.Context, *SetActivityRequest) (*SetActivityResponse, error)
	GetActivity(context.Context, *GetActivityRequest) (*GetActivityResponse, error)
	GetPayOrderPersonTime(context.Context, *GetPayOrderPersonTimeRequest) (*GetPayOrderPersonTimeResponse, error)
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/AddOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrder(ctx, req.(*AddOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/DelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DelOrder(ctx, req.(*DelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_PayOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PayOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/PayOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PayOrder(ctx, req.(*PayOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_SetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).SetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/SetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).SetActivity(ctx, req.(*SetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetActivity(ctx, req.(*GetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetPayOrderPersonTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayOrderPersonTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetPayOrderPersonTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetPayOrderPersonTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetPayOrderPersonTime(ctx, req.(*GetPayOrderPersonTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrder",
			Handler:    _OrderService_AddOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "DelOrder",
			Handler:    _OrderService_DelOrder_Handler,
		},
		{
			MethodName: "PayOrder",
			Handler:    _OrderService_PayOrder_Handler,
		},
		{
			MethodName: "SetActivity",
			Handler:    _OrderService_SetActivity_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _OrderService_GetActivity_Handler,
		},
		{
			MethodName: "GetPayOrderPersonTime",
			Handler:    _OrderService_GetPayOrderPersonTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
