// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package article

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticleInfo struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (m *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(m, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

func (m *ArticleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AddArticleRequest struct {
	ArticleInfo          *ArticleInfo `protobuf:"bytes,1,opt,name=articleInfo,proto3" json:"articleInfo,omitempty"`
	UserID               string       `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddArticleRequest) Reset()         { *m = AddArticleRequest{} }
func (m *AddArticleRequest) String() string { return proto.CompactTextString(m) }
func (*AddArticleRequest) ProtoMessage()    {}
func (*AddArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{1}
}

func (m *AddArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddArticleRequest.Unmarshal(m, b)
}
func (m *AddArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddArticleRequest.Marshal(b, m, deterministic)
}
func (m *AddArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddArticleRequest.Merge(m, src)
}
func (m *AddArticleRequest) XXX_Size() int {
	return xxx_messageInfo_AddArticleRequest.Size(m)
}
func (m *AddArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddArticleRequest proto.InternalMessageInfo

func (m *AddArticleRequest) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

func (m *AddArticleRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type AddArticleResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	ArticleID            string   `protobuf:"bytes,3,opt,name=articleID,proto3" json:"articleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddArticleResponse) Reset()         { *m = AddArticleResponse{} }
func (m *AddArticleResponse) String() string { return proto.CompactTextString(m) }
func (*AddArticleResponse) ProtoMessage()    {}
func (*AddArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{2}
}

func (m *AddArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddArticleResponse.Unmarshal(m, b)
}
func (m *AddArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddArticleResponse.Marshal(b, m, deterministic)
}
func (m *AddArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddArticleResponse.Merge(m, src)
}
func (m *AddArticleResponse) XXX_Size() int {
	return xxx_messageInfo_AddArticleResponse.Size(m)
}
func (m *AddArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddArticleResponse proto.InternalMessageInfo

func (m *AddArticleResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddArticleResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *AddArticleResponse) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

type GetArticleRequest struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleRequest) Reset()         { *m = GetArticleRequest{} }
func (m *GetArticleRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleRequest) ProtoMessage()    {}
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{3}
}

func (m *GetArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleRequest.Unmarshal(m, b)
}
func (m *GetArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleRequest.Merge(m, src)
}
func (m *GetArticleRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleRequest.Size(m)
}
func (m *GetArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleRequest proto.InternalMessageInfo

func (m *GetArticleRequest) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

type GetArticleResponse struct {
	Code                 uint32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string       `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	ArticleInfo          *ArticleInfo `protobuf:"bytes,3,opt,name=articleInfo,proto3" json:"articleInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetArticleResponse) Reset()         { *m = GetArticleResponse{} }
func (m *GetArticleResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleResponse) ProtoMessage()    {}
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{4}
}

func (m *GetArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleResponse.Unmarshal(m, b)
}
func (m *GetArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleResponse.Merge(m, src)
}
func (m *GetArticleResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleResponse.Size(m)
}
func (m *GetArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleResponse proto.InternalMessageInfo

func (m *GetArticleResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetArticleResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetArticleResponse) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

type GetArticleListRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	NumPerPage           int64    `protobuf:"varint,2,opt,name=numPerPage,proto3" json:"numPerPage,omitempty"`
	LastArticleID        string   `protobuf:"bytes,3,opt,name=lastArticleID,proto3" json:"lastArticleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{5}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetArticleListRequest) GetNumPerPage() int64 {
	if m != nil {
		return m.NumPerPage
	}
	return 0
}

func (m *GetArticleListRequest) GetLastArticleID() string {
	if m != nil {
		return m.LastArticleID
	}
	return ""
}

type GetArticleListResponse struct {
	Code                 uint32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string         `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	ArticleInfos         []*ArticleInfo `protobuf:"bytes,3,rep,name=articleInfos,proto3" json:"articleInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetArticleListResponse) Reset()         { *m = GetArticleListResponse{} }
func (m *GetArticleListResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleListResponse) ProtoMessage()    {}
func (*GetArticleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{6}
}

func (m *GetArticleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListResponse.Unmarshal(m, b)
}
func (m *GetArticleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListResponse.Merge(m, src)
}
func (m *GetArticleListResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleListResponse.Size(m)
}
func (m *GetArticleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListResponse proto.InternalMessageInfo

func (m *GetArticleListResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetArticleListResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetArticleListResponse) GetArticleInfos() []*ArticleInfo {
	if m != nil {
		return m.ArticleInfos
	}
	return nil
}

type DelArticleRequest struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelArticleRequest) Reset()         { *m = DelArticleRequest{} }
func (m *DelArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DelArticleRequest) ProtoMessage()    {}
func (*DelArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{7}
}

func (m *DelArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelArticleRequest.Unmarshal(m, b)
}
func (m *DelArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelArticleRequest.Marshal(b, m, deterministic)
}
func (m *DelArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelArticleRequest.Merge(m, src)
}
func (m *DelArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DelArticleRequest.Size(m)
}
func (m *DelArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelArticleRequest proto.InternalMessageInfo

func (m *DelArticleRequest) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

type DelArticleResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelArticleResponse) Reset()         { *m = DelArticleResponse{} }
func (m *DelArticleResponse) String() string { return proto.CompactTextString(m) }
func (*DelArticleResponse) ProtoMessage()    {}
func (*DelArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{8}
}

func (m *DelArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelArticleResponse.Unmarshal(m, b)
}
func (m *DelArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelArticleResponse.Marshal(b, m, deterministic)
}
func (m *DelArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelArticleResponse.Merge(m, src)
}
func (m *DelArticleResponse) XXX_Size() int {
	return xxx_messageInfo_DelArticleResponse.Size(m)
}
func (m *DelArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelArticleResponse proto.InternalMessageInfo

func (m *DelArticleResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelArticleResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type ModifyArticleInfoRequest struct {
	ArticleInfo          *ArticleInfo `protobuf:"bytes,1,opt,name=articleInfo,proto3" json:"articleInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ModifyArticleInfoRequest) Reset()         { *m = ModifyArticleInfoRequest{} }
func (m *ModifyArticleInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyArticleInfoRequest) ProtoMessage()    {}
func (*ModifyArticleInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{9}
}

func (m *ModifyArticleInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyArticleInfoRequest.Unmarshal(m, b)
}
func (m *ModifyArticleInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyArticleInfoRequest.Marshal(b, m, deterministic)
}
func (m *ModifyArticleInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyArticleInfoRequest.Merge(m, src)
}
func (m *ModifyArticleInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyArticleInfoRequest.Size(m)
}
func (m *ModifyArticleInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyArticleInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyArticleInfoRequest proto.InternalMessageInfo

func (m *ModifyArticleInfoRequest) GetArticleInfo() *ArticleInfo {
	if m != nil {
		return m.ArticleInfo
	}
	return nil
}

type ModifyArticleInfoResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyArticleInfoResponse) Reset()         { *m = ModifyArticleInfoResponse{} }
func (m *ModifyArticleInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyArticleInfoResponse) ProtoMessage()    {}
func (*ModifyArticleInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{10}
}

func (m *ModifyArticleInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyArticleInfoResponse.Unmarshal(m, b)
}
func (m *ModifyArticleInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyArticleInfoResponse.Marshal(b, m, deterministic)
}
func (m *ModifyArticleInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyArticleInfoResponse.Merge(m, src)
}
func (m *ModifyArticleInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyArticleInfoResponse.Size(m)
}
func (m *ModifyArticleInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyArticleInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyArticleInfoResponse proto.InternalMessageInfo

func (m *ModifyArticleInfoResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModifyArticleInfoResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ArticleInfo)(nil), "article.ArticleInfo")
	proto.RegisterType((*AddArticleRequest)(nil), "article.AddArticleRequest")
	proto.RegisterType((*AddArticleResponse)(nil), "article.AddArticleResponse")
	proto.RegisterType((*GetArticleRequest)(nil), "article.GetArticleRequest")
	proto.RegisterType((*GetArticleResponse)(nil), "article.GetArticleResponse")
	proto.RegisterType((*GetArticleListRequest)(nil), "article.GetArticleListRequest")
	proto.RegisterType((*GetArticleListResponse)(nil), "article.GetArticleListResponse")
	proto.RegisterType((*DelArticleRequest)(nil), "article.DelArticleRequest")
	proto.RegisterType((*DelArticleResponse)(nil), "article.DelArticleResponse")
	proto.RegisterType((*ModifyArticleInfoRequest)(nil), "article.ModifyArticleInfoRequest")
	proto.RegisterType((*ModifyArticleInfoResponse)(nil), "article.ModifyArticleInfoResponse")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2) }

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x0f, 0xd2, 0x30,
	0x14, 0xc7, 0x81, 0x22, 0x84, 0x87, 0x90, 0xf0, 0x82, 0x64, 0x4e, 0x83, 0xd8, 0x78, 0xe0, 0x44,
	0x22, 0x26, 0xc6, 0x2b, 0x86, 0x84, 0x2c, 0x91, 0x84, 0x8c, 0xab, 0x07, 0xe7, 0x56, 0xc8, 0x92,
	0xb9, 0xc2, 0x5a, 0x4c, 0xf4, 0xe4, 0x5f, 0xe2, 0xdf, 0x6a, 0xd6, 0x6d, 0xac, 0xdb, 0x80, 0xe8,
	0xbc, 0xf5, 0xf5, 0xad, 0xdf, 0xf7, 0x79, 0xbf, 0x06, 0x03, 0x27, 0x92, 0xbe, 0x1b, 0xb0, 0xc5,
	0x29, 0xe2, 0x92, 0x63, 0x37, 0x35, 0x29, 0x87, 0xfe, 0x2a, 0x39, 0x5a, 0xe1, 0x81, 0xe3, 0x4b,
	0xe8, 0xa5, 0x1e, 0x6b, 0x6d, 0x34, 0x67, 0xcd, 0x79, 0xcf, 0xce, 0x2f, 0x70, 0x0c, 0x4f, 0xa4,
	0x2f, 0x03, 0x66, 0xb4, 0x94, 0x27, 0x31, 0xd0, 0x80, 0xae, 0xcb, 0x43, 0xc9, 0x42, 0x69, 0x10,
	0x75, 0x9f, 0x99, 0x88, 0xd0, 0x96, 0xce, 0x51, 0x18, 0xed, 0x19, 0x99, 0xf7, 0x6c, 0x75, 0xa6,
	0x2e, 0x8c, 0x56, 0x9e, 0x97, 0xc6, 0xb4, 0xd9, 0xf9, 0xc2, 0x84, 0xc4, 0xf7, 0xd0, 0x77, 0x72,
	0x0a, 0x15, 0xb8, 0xbf, 0x1c, 0x2f, 0x32, 0x66, 0x8d, 0xd0, 0xd6, 0x3f, 0xc4, 0x09, 0x74, 0x2e,
	0x82, 0x45, 0xd6, 0x3a, 0x25, 0x4a, 0x2d, 0xfa, 0x05, 0x50, 0x0f, 0x22, 0x4e, 0x3c, 0x14, 0x2c,
	0xc6, 0x71, 0xb9, 0xc7, 0x94, 0xfc, 0xc0, 0x56, 0xe7, 0x04, 0xde, 0x63, 0x5b, 0x71, 0x4c, 0x25,
	0x32, 0xb3, 0x58, 0x0a, 0x52, 0x2a, 0x05, 0x7d, 0x0b, 0xa3, 0x0d, 0x93, 0xa5, 0x34, 0x1e, 0x56,
	0x8f, 0xfe, 0x04, 0xd4, 0x9f, 0xd4, 0x82, 0x2a, 0x15, 0x8a, 0xfc, 0x65, 0xa1, 0xe8, 0x19, 0x9e,
	0xe5, 0xb1, 0x3f, 0xf9, 0x42, 0x66, 0xc8, 0x08, 0xed, 0x93, 0x73, 0x4c, 0xc2, 0x13, 0x5b, 0x9d,
	0x71, 0x0a, 0x10, 0x5e, 0xbe, 0xed, 0x58, 0xb4, 0x8b, 0x3d, 0x2d, 0xe5, 0xd1, 0x6e, 0xf0, 0x0d,
	0x0c, 0x02, 0x47, 0x64, 0x6a, 0xd7, 0xea, 0x14, 0x2f, 0xe9, 0xaf, 0x26, 0x4c, 0xca, 0x31, 0x6b,
	0xe5, 0xfc, 0x01, 0x9e, 0x6a, 0xa9, 0x08, 0x83, 0xcc, 0xc8, 0xdd, 0xa4, 0x0b, 0x5f, 0xc6, 0x4d,
	0x5a, 0xb3, 0xe0, 0x9f, 0x9a, 0xf4, 0x11, 0x50, 0x7f, 0x52, 0x07, 0x98, 0xda, 0x60, 0x6c, 0xb9,
	0xe7, 0x1f, 0x7e, 0xe8, 0x64, 0xff, 0x37, 0xe9, 0xd4, 0x82, 0xe7, 0x37, 0x34, 0xeb, 0xe0, 0x2d,
	0x7f, 0x13, 0x18, 0xa6, 0x2a, 0x7b, 0x16, 0x7d, 0xf7, 0x5d, 0x86, 0x1b, 0x80, 0x7c, 0x5f, 0xd0,
	0xcc, 0x71, 0xca, 0x9b, 0x6a, 0xbe, 0xb8, 0xe9, 0x4b, 0x38, 0x68, 0x23, 0x16, 0xca, 0x7b, 0xae,
	0x09, 0x55, 0x76, 0x45, 0x13, 0xaa, 0x2e, 0x05, 0x6d, 0xe0, 0x1e, 0x86, 0xc5, 0xe1, 0xc1, 0xe9,
	0x8d, 0x07, 0xda, 0x24, 0x9b, 0xaf, 0xee, 0xfa, 0x75, 0xba, 0xbc, 0xb9, 0x1a, 0x5d, 0x65, 0x48,
	0x34, 0xba, 0xea, 0x34, 0xd0, 0x06, 0x7e, 0x86, 0x51, 0xa5, 0x1b, 0xf8, 0xfa, 0xfa, 0xe6, 0x5e,
	0xf7, 0x4d, 0xfa, 0xe8, 0x93, 0x4c, 0xfd, 0x6b, 0x47, 0xfd, 0xa3, 0xdf, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xc0, 0x37, 0x43, 0xd7, 0xb4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleServiceClient interface {
	AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*AddArticleResponse, error)
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
	GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error)
	DelArticle(ctx context.Context, in *DelArticleRequest, opts ...grpc.CallOption) (*DelArticleResponse, error)
	ModifyArticleInfo(ctx context.Context, in *ModifyArticleInfoRequest, opts ...grpc.CallOption) (*ModifyArticleInfoResponse, error)
}

type articleServiceClient struct {
	cc *grpc.ClientConn
}

func NewArticleServiceClient(cc *grpc.ClientConn) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) AddArticle(ctx context.Context, in *AddArticleRequest, opts ...grpc.CallOption) (*AddArticleResponse, error) {
	out := new(AddArticleResponse)
	err := c.cc.Invoke(ctx, "/article.ArticleService/AddArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	out := new(GetArticleResponse)
	err := c.cc.Invoke(ctx, "/article.ArticleService/GetArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error) {
	out := new(GetArticleListResponse)
	err := c.cc.Invoke(ctx, "/article.ArticleService/GetArticleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) DelArticle(ctx context.Context, in *DelArticleRequest, opts ...grpc.CallOption) (*DelArticleResponse, error) {
	out := new(DelArticleResponse)
	err := c.cc.Invoke(ctx, "/article.ArticleService/DelArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) ModifyArticleInfo(ctx context.Context, in *ModifyArticleInfoRequest, opts ...grpc.CallOption) (*ModifyArticleInfoResponse, error) {
	out := new(ModifyArticleInfoResponse)
	err := c.cc.Invoke(ctx, "/article.ArticleService/ModifyArticleInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
type ArticleServiceServer interface {
	AddArticle(context.Context, *AddArticleRequest) (*AddArticleResponse, error)
	GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error)
	GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListResponse, error)
	DelArticle(context.Context, *DelArticleRequest) (*DelArticleResponse, error)
	ModifyArticleInfo(context.Context, *ModifyArticleInfoRequest) (*ModifyArticleInfoResponse, error)
}

func RegisterArticleServiceServer(s *grpc.Server, srv ArticleServiceServer) {
	s.RegisterService(&_ArticleService_serviceDesc, srv)
}

func _ArticleService_AddArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).AddArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleService/AddArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).AddArticle(ctx, req.(*AddArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleService/GetArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleService/GetArticleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleList(ctx, req.(*GetArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_DelArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).DelArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleService/DelArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).DelArticle(ctx, req.(*DelArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_ModifyArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyArticleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).ModifyArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.ArticleService/ModifyArticleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).ModifyArticleInfo(ctx, req.(*ModifyArticleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddArticle",
			Handler:    _ArticleService_AddArticle_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _ArticleService_GetArticle_Handler,
		},
		{
			MethodName: "GetArticleList",
			Handler:    _ArticleService_GetArticleList_Handler,
		},
		{
			MethodName: "DelArticle",
			Handler:    _ArticleService_DelArticle_Handler,
		},
		{
			MethodName: "ModifyArticleInfo",
			Handler:    _ArticleService_ModifyArticleInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
