# app config
log:
  logPath: log/user_service.log            # 日志文件路径
  logLevel: info

etcd:
  endpoints:
    - 192.168.1.7:2379
    - 192.168.1.10:2379
    - 192.168.1.11:2379

grpcServer:
  name: user-core-service
  port: 6068

httpServer:
  port: 4582

database:
  address: 192.168.1.100:3306
  username: root
  password: 180498
  driverName: mysql
  dbName: ant_test