[[exchange]]
name = "bybit"
access_key = ""
secret_key = ""
testnet = true
websocket = false

[log]
path = "./app.log"
level = "debug"

[option]
symbol = "BTCUSD"
direction = 1              # 方向: 1(UP) -1(Down)
grid_num = 10              # 网格节点数量 10
grid_point_amount = 1.0    # 网格节点下单量 1
grid_point_dis = 20.0      # 网格节点间距 20
grid_cov_dis = 50.0        # 网格节点平仓价差 50
