[[exchange]]
name = "binancefutures"
access_key = "UE52gPqlyFk5Veaz5r7noCY0iuyuBPV8cRVrYGddQGjPEZ0XcLy3Tnp0BJdBFo0t"
secret_key = "9bLIwDfsicq6HlYvIEgRtlhhPIxob8kbkRJWFay3XECoYAS6ZXF0HJUZCTaOrSNh"
testnet = false
websocket = false
debug_mode = false
passphrase = ""

[log]
path = "./app.log"
level = "debug"

[option]
symbol = "DOGEUSDT"
direction = 1              # 方向: 1(UP) -1(Down)
grid_num = 10              # 网格节点数量 10
grid_point_amount = 1.0    # 网格节点下单量 1
grid_point_dis = 0.02      # 网格节点间距 20
grid_cov_dis = 0.05        # 网格节点平仓价差 50
