// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WxUserInfo struct {
	RawData              string   `protobuf:"bytes,1,opt,name=rawData,proto3" json:"rawData,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	EncryptedData        string   `protobuf:"bytes,3,opt,name=encryptedData,proto3" json:"encryptedData,omitempty"`
	Iv                   string   `protobuf:"bytes,4,opt,name=iv,proto3" json:"iv,omitempty"`
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxUserInfo) Reset()         { *m = WxUserInfo{} }
func (m *WxUserInfo) String() string { return proto.CompactTextString(m) }
func (*WxUserInfo) ProtoMessage()    {}
func (*WxUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *WxUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxUserInfo.Unmarshal(m, b)
}
func (m *WxUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxUserInfo.Marshal(b, m, deterministic)
}
func (m *WxUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxUserInfo.Merge(m, src)
}
func (m *WxUserInfo) XXX_Size() int {
	return xxx_messageInfo_WxUserInfo.Size(m)
}
func (m *WxUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WxUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WxUserInfo proto.InternalMessageInfo

func (m *WxUserInfo) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *WxUserInfo) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *WxUserInfo) GetEncryptedData() string {
	if m != nil {
		return m.EncryptedData
	}
	return ""
}

func (m *WxUserInfo) GetIv() string {
	if m != nil {
		return m.Iv
	}
	return ""
}

func (m *WxUserInfo) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type DecryptWxUserInfoRequest struct {
	UserID               string      `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	WxUserInfo           *WxUserInfo `protobuf:"bytes,2,opt,name=wxUserInfo,proto3" json:"wxUserInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DecryptWxUserInfoRequest) Reset()         { *m = DecryptWxUserInfoRequest{} }
func (m *DecryptWxUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptWxUserInfoRequest) ProtoMessage()    {}
func (*DecryptWxUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *DecryptWxUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptWxUserInfoRequest.Unmarshal(m, b)
}
func (m *DecryptWxUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptWxUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *DecryptWxUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptWxUserInfoRequest.Merge(m, src)
}
func (m *DecryptWxUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DecryptWxUserInfoRequest.Size(m)
}
func (m *DecryptWxUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptWxUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptWxUserInfoRequest proto.InternalMessageInfo

func (m *DecryptWxUserInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DecryptWxUserInfoRequest) GetWxUserInfo() *WxUserInfo {
	if m != nil {
		return m.WxUserInfo
	}
	return nil
}

type DecryptWxUserInfoResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	WxUserInfoData       string   `protobuf:"bytes,3,opt,name=wxUserInfoData,proto3" json:"wxUserInfoData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptWxUserInfoResponse) Reset()         { *m = DecryptWxUserInfoResponse{} }
func (m *DecryptWxUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*DecryptWxUserInfoResponse) ProtoMessage()    {}
func (*DecryptWxUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *DecryptWxUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptWxUserInfoResponse.Unmarshal(m, b)
}
func (m *DecryptWxUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptWxUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *DecryptWxUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptWxUserInfoResponse.Merge(m, src)
}
func (m *DecryptWxUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_DecryptWxUserInfoResponse.Size(m)
}
func (m *DecryptWxUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptWxUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptWxUserInfoResponse proto.InternalMessageInfo

func (m *DecryptWxUserInfoResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DecryptWxUserInfoResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *DecryptWxUserInfoResponse) GetWxUserInfoData() string {
	if m != nil {
		return m.WxUserInfoData
	}
	return ""
}

type LoginRequest struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdentityNo           string      `protobuf:"bytes,2,opt,name=identityNo,proto3" json:"identityNo,omitempty"`
	PhoneNumber          string      `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string      `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	WxUserInfo           *WxUserInfo `protobuf:"bytes,5,opt,name=wxUserInfo,proto3" json:"wxUserInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginRequest) GetIdentityNo() string {
	if m != nil {
		return m.IdentityNo
	}
	return ""
}

func (m *LoginRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetWxUserInfo() *WxUserInfo {
	if m != nil {
		return m.WxUserInfo
	}
	return nil
}

type LoginResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *LoginResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdentityNo           string   `protobuf:"bytes,2,opt,name=identityNo,proto3" json:"identityNo,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender               uint32   `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetIdentityNo() string {
	if m != nil {
		return m.IdentityNo
	}
	return ""
}

func (m *UserInfo) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdentityNo           string   `protobuf:"bytes,2,opt,name=identityNo,proto3" json:"identityNo,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender               uint32   `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddUserRequest) GetIdentityNo() string {
	if m != nil {
		return m.IdentityNo
	}
	return ""
}

func (m *AddUserRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *AddUserRequest) GetGender() uint32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *AddUserRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AddUserResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddUserResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *AddUserResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUserResponse struct {
	Code                 uint32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string    `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	UserInfo             *UserInfo `protobuf:"bytes,3,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUserResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetUserResponse) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type DelUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserRequest) Reset()         { *m = DelUserRequest{} }
func (m *DelUserRequest) String() string { return proto.CompactTextString(m) }
func (*DelUserRequest) ProtoMessage()    {}
func (*DelUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *DelUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserRequest.Unmarshal(m, b)
}
func (m *DelUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserRequest.Marshal(b, m, deterministic)
}
func (m *DelUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserRequest.Merge(m, src)
}
func (m *DelUserRequest) XXX_Size() int {
	return xxx_messageInfo_DelUserRequest.Size(m)
}
func (m *DelUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserRequest proto.InternalMessageInfo

func (m *DelUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DelUserResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserResponse) Reset()         { *m = DelUserResponse{} }
func (m *DelUserResponse) String() string { return proto.CompactTextString(m) }
func (*DelUserResponse) ProtoMessage()    {}
func (*DelUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *DelUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserResponse.Unmarshal(m, b)
}
func (m *DelUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserResponse.Marshal(b, m, deterministic)
}
func (m *DelUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserResponse.Merge(m, src)
}
func (m *DelUserResponse) XXX_Size() int {
	return xxx_messageInfo_DelUserResponse.Size(m)
}
func (m *DelUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserResponse proto.InternalMessageInfo

func (m *DelUserResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DelUserResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type ModifyUserInfoRequest struct {
	UserID               string    `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserInfo             *UserInfo `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModifyUserInfoRequest) Reset()         { *m = ModifyUserInfoRequest{} }
func (m *ModifyUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyUserInfoRequest) ProtoMessage()    {}
func (*ModifyUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *ModifyUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserInfoRequest.Unmarshal(m, b)
}
func (m *ModifyUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *ModifyUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserInfoRequest.Merge(m, src)
}
func (m *ModifyUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyUserInfoRequest.Size(m)
}
func (m *ModifyUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserInfoRequest proto.InternalMessageInfo

func (m *ModifyUserInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ModifyUserInfoRequest) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type ModifyUserInfoResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyUserInfoResponse) Reset()         { *m = ModifyUserInfoResponse{} }
func (m *ModifyUserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyUserInfoResponse) ProtoMessage()    {}
func (*ModifyUserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *ModifyUserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyUserInfoResponse.Unmarshal(m, b)
}
func (m *ModifyUserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyUserInfoResponse.Marshal(b, m, deterministic)
}
func (m *ModifyUserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyUserInfoResponse.Merge(m, src)
}
func (m *ModifyUserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyUserInfoResponse.Size(m)
}
func (m *ModifyUserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyUserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyUserInfoResponse proto.InternalMessageInfo

func (m *ModifyUserInfoResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ModifyUserInfoResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

type GetUserIdByPhoneNumberRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIdByPhoneNumberRequest) Reset()         { *m = GetUserIdByPhoneNumberRequest{} }
func (m *GetUserIdByPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserIdByPhoneNumberRequest) ProtoMessage()    {}
func (*GetUserIdByPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *GetUserIdByPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIdByPhoneNumberRequest.Unmarshal(m, b)
}
func (m *GetUserIdByPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIdByPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetUserIdByPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIdByPhoneNumberRequest.Merge(m, src)
}
func (m *GetUserIdByPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserIdByPhoneNumberRequest.Size(m)
}
func (m *GetUserIdByPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIdByPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIdByPhoneNumberRequest proto.InternalMessageInfo

func (m *GetUserIdByPhoneNumberRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type GetUserIdByPhoneNumberResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserIdByPhoneNumberResponse) Reset()         { *m = GetUserIdByPhoneNumberResponse{} }
func (m *GetUserIdByPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserIdByPhoneNumberResponse) ProtoMessage()    {}
func (*GetUserIdByPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *GetUserIdByPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserIdByPhoneNumberResponse.Unmarshal(m, b)
}
func (m *GetUserIdByPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserIdByPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *GetUserIdByPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserIdByPhoneNumberResponse.Merge(m, src)
}
func (m *GetUserIdByPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserIdByPhoneNumberResponse.Size(m)
}
func (m *GetUserIdByPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserIdByPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserIdByPhoneNumberResponse proto.InternalMessageInfo

func (m *GetUserIdByPhoneNumberResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUserIdByPhoneNumberResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetUserIdByPhoneNumberResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetUsersByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByNameRequest) Reset()         { *m = GetUsersByNameRequest{} }
func (m *GetUsersByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersByNameRequest) ProtoMessage()    {}
func (*GetUsersByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *GetUsersByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByNameRequest.Unmarshal(m, b)
}
func (m *GetUsersByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByNameRequest.Merge(m, src)
}
func (m *GetUsersByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersByNameRequest.Size(m)
}
func (m *GetUsersByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByNameRequest proto.InternalMessageInfo

func (m *GetUsersByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUsersByNameResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	CodeMsg              string   `protobuf:"bytes,2,opt,name=codeMsg,proto3" json:"codeMsg,omitempty"`
	UserIDList           []string `protobuf:"bytes,3,rep,name=userIDList,proto3" json:"userIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByNameResponse) Reset()         { *m = GetUsersByNameResponse{} }
func (m *GetUsersByNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersByNameResponse) ProtoMessage()    {}
func (*GetUsersByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{17}
}

func (m *GetUsersByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByNameResponse.Unmarshal(m, b)
}
func (m *GetUsersByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByNameResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByNameResponse.Merge(m, src)
}
func (m *GetUsersByNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersByNameResponse.Size(m)
}
func (m *GetUsersByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByNameResponse proto.InternalMessageInfo

func (m *GetUsersByNameResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUsersByNameResponse) GetCodeMsg() string {
	if m != nil {
		return m.CodeMsg
	}
	return ""
}

func (m *GetUsersByNameResponse) GetUserIDList() []string {
	if m != nil {
		return m.UserIDList
	}
	return nil
}

func init() {
	proto.RegisterType((*WxUserInfo)(nil), "user.WxUserInfo")
	proto.RegisterType((*DecryptWxUserInfoRequest)(nil), "user.DecryptWxUserInfoRequest")
	proto.RegisterType((*DecryptWxUserInfoResponse)(nil), "user.DecryptWxUserInfoResponse")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*AddUserRequest)(nil), "user.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "user.AddUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.GetUserResponse")
	proto.RegisterType((*DelUserRequest)(nil), "user.DelUserRequest")
	proto.RegisterType((*DelUserResponse)(nil), "user.DelUserResponse")
	proto.RegisterType((*ModifyUserInfoRequest)(nil), "user.ModifyUserInfoRequest")
	proto.RegisterType((*ModifyUserInfoResponse)(nil), "user.ModifyUserInfoResponse")
	proto.RegisterType((*GetUserIdByPhoneNumberRequest)(nil), "user.GetUserIdByPhoneNumberRequest")
	proto.RegisterType((*GetUserIdByPhoneNumberResponse)(nil), "user.GetUserIdByPhoneNumberResponse")
	proto.RegisterType((*GetUsersByNameRequest)(nil), "user.GetUsersByNameRequest")
	proto.RegisterType((*GetUsersByNameResponse)(nil), "user.GetUsersByNameResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x6e, 0x12, 0x4f,
	0x14, 0x66, 0x59, 0xa0, 0xed, 0xe1, 0xc7, 0xd2, 0xdf, 0x58, 0xc8, 0x8a, 0x15, 0xc9, 0xd8, 0x98,
	0x46, 0x93, 0xc6, 0xe0, 0x8d, 0x77, 0xa6, 0x0d, 0xd1, 0x90, 0x14, 0x62, 0x30, 0xb5, 0x17, 0x5e,
	0x6d, 0xd9, 0x03, 0x6e, 0x2c, 0xbb, 0x74, 0x77, 0xa1, 0xf2, 0x12, 0x3e, 0x83, 0x57, 0x5e, 0xf9,
	0x28, 0x3e, 0x94, 0x99, 0xd9, 0x99, 0xfd, 0xd7, 0x05, 0xc9, 0x5a, 0xaf, 0x98, 0x39, 0x73, 0xfe,
	0x7c, 0xe7, 0x9b, 0xef, 0x30, 0x0b, 0xb0, 0xf0, 0xd0, 0x3d, 0x99, 0xbb, 0x8e, 0xef, 0x90, 0x12,
	0x5b, 0xd3, 0x6f, 0x0a, 0xc0, 0xe5, 0xd7, 0x0b, 0x0f, 0xdd, 0xbe, 0x3d, 0x71, 0x88, 0x0e, 0x3b,
	0xae, 0x71, 0xdb, 0x33, 0x7c, 0x43, 0x57, 0x3a, 0xca, 0xf1, 0xde, 0x48, 0x6e, 0xc9, 0x21, 0xec,
	0x79, 0xd6, 0xd4, 0x36, 0xfc, 0x85, 0x8b, 0x7a, 0x91, 0x9f, 0x45, 0x06, 0x72, 0x04, 0x35, 0xb4,
	0xc7, 0xee, 0x6a, 0xee, 0xa3, 0xc9, 0xa3, 0x55, 0xee, 0x91, 0x34, 0x12, 0x0d, 0x8a, 0xd6, 0x52,
	0x2f, 0xf1, 0xa3, 0xa2, 0xb5, 0x24, 0x04, 0x4a, 0x63, 0xc7, 0x44, 0xbd, 0xcc, 0x2d, 0x7c, 0x4d,
	0x4d, 0xd0, 0x7b, 0xc8, 0x83, 0x22, 0x58, 0x23, 0xbc, 0x59, 0xa0, 0xe7, 0x93, 0x26, 0x54, 0x18,
	0xe8, 0x7e, 0x4f, 0x80, 0x13, 0x3b, 0xf2, 0x12, 0xe0, 0x36, 0x74, 0xe6, 0xe0, 0xaa, 0xdd, 0xfd,
	0x13, 0xde, 0x6b, 0x2c, 0x49, 0xcc, 0x87, 0xde, 0xc0, 0xc3, 0x8c, 0x2a, 0xde, 0xdc, 0xb1, 0x3d,
	0x0c, 0x61, 0xb1, 0x22, 0xb5, 0x00, 0x16, 0x23, 0x86, 0xfd, 0x0e, 0xbc, 0xa9, 0x68, 0x5e, 0x6e,
	0xc9, 0x33, 0xd0, 0xa2, 0xc4, 0xb1, 0xde, 0x53, 0x56, 0xfa, 0x53, 0x81, 0xff, 0xce, 0x9d, 0xa9,
	0x65, 0xcb, 0x6e, 0x08, 0x94, 0x6c, 0x63, 0x86, 0xa2, 0x17, 0xbe, 0x26, 0x6d, 0x00, 0xcb, 0x44,
	0xdb, 0xb7, 0xfc, 0xd5, 0xd0, 0x11, 0x95, 0x62, 0x16, 0xd2, 0x81, 0xea, 0xfc, 0xb3, 0x63, 0xe3,
	0x70, 0x31, 0xbb, 0x42, 0x57, 0x54, 0x8a, 0x9b, 0xc8, 0x01, 0x94, 0x71, 0x66, 0x58, 0xd7, 0x82,
	0xe6, 0x60, 0x93, 0x62, 0xa8, 0xbc, 0x05, 0x43, 0x17, 0x50, 0x13, 0x68, 0x73, 0xb1, 0x12, 0x5d,
	0x95, 0x1a, 0xbf, 0x2a, 0xfa, 0x5d, 0x81, 0xdd, 0x50, 0x6d, 0x79, 0x18, 0xd8, 0x07, 0xd5, 0x98,
	0x22, 0xcf, 0x5a, 0x1b, 0xb1, 0x25, 0x2b, 0x35, 0x45, 0xdb, 0x44, 0x97, 0xb7, 0x5c, 0x1b, 0x89,
	0x5d, 0x9a, 0xab, 0xf2, 0x06, 0xae, 0x2a, 0x31, 0xae, 0xe8, 0x0f, 0x05, 0xb4, 0x53, 0xd3, 0x64,
	0x28, 0xff, 0xe6, 0xaa, 0xfe, 0x3d, 0xd0, 0x4b, 0xa8, 0x87, 0x38, 0xef, 0xf5, 0x92, 0x8e, 0x41,
	0x7b, 0x87, 0x7e, 0x9c, 0x80, 0x35, 0x93, 0x47, 0xbf, 0x40, 0x3d, 0xf4, 0xcc, 0x05, 0xe1, 0x39,
	0xec, 0x2e, 0xa4, 0x2c, 0x55, 0x2e, 0x4b, 0x2d, 0x90, 0x65, 0x28, 0xca, 0xf0, 0x9c, 0xc1, 0xea,
	0xe1, 0xf5, 0x36, 0xb0, 0xde, 0x40, 0x3d, 0xf4, 0xcc, 0x03, 0x8b, 0x7e, 0x82, 0xc6, 0xc0, 0x31,
	0xad, 0xc9, 0x6a, 0xdb, 0xbf, 0xa0, 0x78, 0x1f, 0xc5, 0x3f, 0xf4, 0xf1, 0x16, 0x9a, 0xe9, 0xe4,
	0xb9, 0x40, 0x9e, 0xc2, 0x63, 0x41, 0x7e, 0xdf, 0x3c, 0x5b, 0xbd, 0x8f, 0xf4, 0x22, 0xc1, 0xa6,
	0x84, 0xa5, 0xdc, 0x11, 0x16, 0x9d, 0x40, 0x7b, 0x5d, 0x8a, 0x7b, 0x55, 0xd4, 0x0b, 0x68, 0x88,
	0x3a, 0xde, 0xd9, 0x6a, 0x68, 0xcc, 0x70, 0xc3, 0x64, 0xd1, 0x09, 0x34, 0xd3, 0xce, 0xb9, 0xc0,
	0xb4, 0x83, 0xf7, 0xae, 0xdf, 0x3b, 0xb7, 0x3c, 0x5f, 0x57, 0x3b, 0x2a, 0x9b, 0xd0, 0xc8, 0xd2,
	0xfd, 0x55, 0x82, 0x2a, 0xab, 0xf2, 0x01, 0xdd, 0xa5, 0x35, 0x46, 0xf2, 0x1a, 0x76, 0xc4, 0x3c,
	0x91, 0x83, 0xe0, 0xf2, 0x92, 0x7f, 0x03, 0xad, 0x46, 0xca, 0x1a, 0xa0, 0xa2, 0x05, 0x16, 0x29,
	0x10, 0xcb, 0xc8, 0xe4, 0xfc, 0xc8, 0xc8, 0xd4, 0xac, 0x04, 0x91, 0x42, 0xa9, 0x32, 0x32, 0x29,
	0x71, 0x19, 0x99, 0x92, 0x33, 0x2d, 0x90, 0x01, 0x68, 0x49, 0x15, 0x91, 0x47, 0x81, 0x6b, 0xa6,
	0x70, 0x5b, 0x87, 0xd9, 0x87, 0x61, 0x3a, 0x0c, 0x49, 0x4f, 0x29, 0x81, 0x3c, 0x4d, 0x60, 0xcf,
	0x96, 0x5a, 0xeb, 0x68, 0xb3, 0x53, 0x1c, 0x75, 0xf2, 0x6e, 0x25, 0xea, 0x4c, 0x79, 0x48, 0xd4,
	0xd9, 0x72, 0xa0, 0x05, 0xd2, 0x85, 0x32, 0x7f, 0xa5, 0x08, 0x09, 0x1c, 0xe3, 0x0f, 0x6c, 0xeb,
	0x41, 0xc2, 0x16, 0xc6, 0x7c, 0x84, 0xff, 0xef, 0xbc, 0xfd, 0xa4, 0x2d, 0x69, 0xce, 0xfe, 0xf4,
	0x68, 0x3d, 0x59, 0x7b, 0x2e, 0xf3, 0x5e, 0x55, 0xf8, 0x77, 0xd5, 0xab, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x22, 0xae, 0xe7, 0x8c, 0x65, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	DelUser(ctx context.Context, in *DelUserRequest, opts ...grpc.CallOption) (*DelUserResponse, error)
	ModifyUserInfo(ctx context.Context, in *ModifyUserInfoRequest, opts ...grpc.CallOption) (*ModifyUserInfoResponse, error)
	GetUserIdByPhoneNumber(ctx context.Context, in *GetUserIdByPhoneNumberRequest, opts ...grpc.CallOption) (*GetUserIdByPhoneNumberResponse, error)
	GetUsersByName(ctx context.Context, in *GetUsersByNameRequest, opts ...grpc.CallOption) (*GetUsersByNameResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	DecryptWxUserInfo(ctx context.Context, in *DecryptWxUserInfoRequest, opts ...grpc.CallOption) (*DecryptWxUserInfoResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelUser(ctx context.Context, in *DelUserRequest, opts ...grpc.CallOption) (*DelUserResponse, error) {
	out := new(DelUserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/DelUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ModifyUserInfo(ctx context.Context, in *ModifyUserInfoRequest, opts ...grpc.CallOption) (*ModifyUserInfoResponse, error) {
	out := new(ModifyUserInfoResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/ModifyUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserIdByPhoneNumber(ctx context.Context, in *GetUserIdByPhoneNumberRequest, opts ...grpc.CallOption) (*GetUserIdByPhoneNumberResponse, error) {
	out := new(GetUserIdByPhoneNumberResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUserIdByPhoneNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsersByName(ctx context.Context, in *GetUsersByNameRequest, opts ...grpc.CallOption) (*GetUsersByNameResponse, error) {
	out := new(GetUsersByNameResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/GetUsersByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DecryptWxUserInfo(ctx context.Context, in *DecryptWxUserInfoRequest, opts ...grpc.CallOption) (*DecryptWxUserInfoResponse, error) {
	out := new(DecryptWxUserInfoResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/DecryptWxUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	DelUser(context.Context, *DelUserRequest) (*DelUserResponse, error)
	ModifyUserInfo(context.Context, *ModifyUserInfoRequest) (*ModifyUserInfoResponse, error)
	GetUserIdByPhoneNumber(context.Context, *GetUserIdByPhoneNumberRequest) (*GetUserIdByPhoneNumberResponse, error)
	GetUsersByName(context.Context, *GetUsersByNameRequest) (*GetUsersByNameResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	DecryptWxUserInfo(context.Context, *DecryptWxUserInfoRequest) (*DecryptWxUserInfoResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DelUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelUser(ctx, req.(*DelUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ModifyUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ModifyUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/ModifyUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ModifyUserInfo(ctx, req.(*ModifyUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserIdByPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdByPhoneNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserIdByPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserIdByPhoneNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserIdByPhoneNumber(ctx, req.(*GetUserIdByPhoneNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsersByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsersByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUsersByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsersByName(ctx, req.(*GetUsersByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DecryptWxUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptWxUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DecryptWxUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/DecryptWxUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DecryptWxUserInfo(ctx, req.(*DecryptWxUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "DelUser",
			Handler:    _UserService_DelUser_Handler,
		},
		{
			MethodName: "ModifyUserInfo",
			Handler:    _UserService_ModifyUserInfo_Handler,
		},
		{
			MethodName: "GetUserIdByPhoneNumber",
			Handler:    _UserService_GetUserIdByPhoneNumber_Handler,
		},
		{
			MethodName: "GetUsersByName",
			Handler:    _UserService_GetUsersByName_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "DecryptWxUserInfo",
			Handler:    _UserService_DecryptWxUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
