# app config
log:
  logPath: log/article_service.log            # 日志文件路径
  logLevel: info

etcd:
  endpoints:
    - 127.0.0.1:2379

server:
  name: article-core-service
  port: 6072

httpServer:
  port: 4585

database:
  address: localhost:3306
  username: root
  password: 180498
  driverName: mysql
  dbName: ant_test

client:
  userServiceName: user-core-service
