apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-deployment
  labels:
    app: ant02
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ant02
  template:
    metadata:
      labels:
        app: ant02
    spec:
      containers:
        - name: app02-d
          image: ants/app02:v1.0
          ports:
            - containerPort: 8081
